In [1]:
#Installing packages
library(data.table)
library(tidyverse)
library(stringi)
library(tidyr)
install.packages("fixest")
library(fixest)
install.packages("estimatr")
library(estimatr)
install.packages("readxl")
library(readxl)
library(zoo)
library(ggplot2)
library(foreign)

── Attaching core tidyverse packages ──────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1
── Conflicts ────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::between()     masks data.table::between()
✖ dplyr::filter()      masks stats::filter()
✖ dplyr::first()       masks data.table::first()
✖ lubridate::hour()    masks data.table::hour()
✖ lubridate::isoweek() masks data.table::isoweek()
✖ dplyr::lag()         masks stats::lag()
✖ dplyr::last()        masks data.table::last()
✖ lubridate::mday()    masks data.table::mday()
✖ lubridate::minute()  masks data.table::minute()
✖ lubridate::month()   masks data.table::month()
✖ lubridate::quarter() masks data.table::quarter()
✖ lubridate::second()  masks data.table::second()
✖ purrr::transpose()   masks data.table::transpose()
✖ lubridate::wday()    masks data.table::wday()
✖ lubridate::week()    masks data.table::week()
✖ lubridate::yday()    masks data.table::yday()
✖ lubridate::year()    masks data.table::year()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Installing package into 'C:/Users/joyse/AppData/Local/R/win-library/4.2'
(as 'lib' is unspecified)

package 'fixest' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'fixest'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem copying C:\Users\joyse\AppData\Local\R\win-library\4.2\00LOCK\fixest\libs\x64\fixest.dll to C:\Users\joyse\AppData\Local\R\win-library\4.2\fixest\libs\x64\fixest.dll: Permission denied"
Warning message:
"restored 'fixest'"

The downloaded binary packages are in
	C:\Users\joyse\AppData\Local\Temp\RtmpIx8gqB\downloaded_packages

Installing package into 'C:/Users/joyse/AppData/Local/R/win-library/4.2'
(as 'lib' is unspecified)

package 'estimatr' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'estimatr'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem copying C:\Users\joyse\AppData\Local\R\win-library\4.2\00LOCK\estimatr\libs\x64\estimatr.dll to C:\Users\joyse\AppData\Local\R\win-library\4.2\estimatr\libs\x64\estimatr.dll: Permission denied"
Warning message:
"restored 'estimatr'"

The downloaded binary packages are in
	C:\Users\joyse\AppData\Local\Temp\RtmpIx8gqB\downloaded_packages

Installing package into 'C:/Users/joyse/AppData/Local/R/win-library/4.2'
(as 'lib' is unspecified)

package 'readxl' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'readxl'"
Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problem copying C:\Users\joyse\AppData\Local\R\win-library\4.2\00LOCK\readxl\libs\x64\readxl.dll to C:\Users\joyse\AppData\Local\R\win-library\4.2\readxl\libs\x64\readxl.dll: Permission denied"
Warning message:
"restored 'readxl'"

The downloaded binary packages are in
	C:\Users\joyse\AppData\Local\Temp\RtmpIx8gqB\downloaded_packages

Attaching package: 'zoo'


The following objects are masked from 'package:base':

    as.Date, as.Date.numeric

In [2]:
#Opening data file
final <- read.csv("C:\\Users\\joyse\\Desktop\\14.33\\Data\\final_merge_withoutB.csv")

# Preprocessing

In [3]:
colnames(final)

  [1] "STATE"
  [2] "Year"
  [3] "Totalpopulation_18to24"
  [4] "Totalpopulation_25to34"
  [5] "Totalpopulation_35to44"
  [6] "Totalpopulation_45to64"
  [7] "Totalpopulation_65"
  [8] "Totalcitizenpopulation_18to24"
  [9] "Totalcitizenpopulation_25to34"
 [10] "Totalcitizenpopulation_35to44"
 [11] "Totalcitizenpopulation_45to64"
 [12] "Totalcitizenpopulation_65"
 [13] "Totalregistered_18to24"
 [14] "Totalregistered_25to34"
 [15] "Totalregistered_35to44"
 [16] "Totalregistered_45to64"
 [17] "Totalregistered_65"
 [18] "PercentregisteredTotal_18to24"
 [19] "PercentregisteredTotal_25to34"
 [20] "PercentregisteredTotal_35to44"
 [21] "PercentregisteredTotal_45to64"
 [22] "PercentregisteredTotal_65"
 [23] "Marginoferrorforpercentregisteredtotal_18to24"
 [24] "Marginoferrorforpercentregisteredtotal_25to34"
 [25] "Marginoferrorforpercentregisteredtotal_35to44"
 [26] "Marginoferrorforpercentregisteredtotal_45to64"
 [27] "Marginoferrorforpercentregisteredtotal_65"
 [28] "PercentregisteredCitizen_18to24"
 [29] "PercentregisteredCitizen_25to34"
 [30] "PercentregisteredCitizen_35to44"
 [31] "PercentregisteredCitizen_45to64"
 [32] "PercentregisteredCitizen_65"
 [33] "Marginoferrorforpercentregisteredcitizen_18to24"
 [34] "Marginoferrorforpercentregisteredcitizen_25to34"
 [35] "Marginoferrorforpercentregisteredcitizen_35to44"
 [36] "Marginoferrorforpercentregisteredcitizen_45to64"
 [37] "Marginoferrorforpercentregisteredcitizen_65"
 [38] "Totalvoted_18to24"
 [39] "Totalvoted_25to34"
 [40] "Totalvoted_35to44"
 [41] "Totalvoted_45to64"
 [42] "Totalvoted_65"
 [43] "PercentvotedTotal_18to24"
 [44] "PercentvotedTotal_25to34"
 [45] "PercentvotedTotal_35to44"
 [46] "PercentvotedTotal_45to64"
 [47] "PercentvotedTotal_65"
 [48] "Marginoferrorpercentvotedtotal_18to24"
 [49] "Marginoferrorpercentvotedtotal_25to34"
 [50] "Marginoferrorpercentvotedtotal_35to44"
 [51] "Marginoferrorpercentvotedtotal_45to64"
 [52] "Marginoferrorpercentvotedtotal_65"
 [53] "PercentvotedCitizen_18to24"
 [54] "PercentvotedCitizen_25to34"
 [55] "PercentvotedCitizen_35to44"
 [56] "PercentvotedCitizen_45to64"
 [57] "PercentvotedCitizen_65"
 [58] "Marginoferrorpercentvotedcitizen_18to24"
 [59] "Marginoferrorpercentvotedcitizen_25to34"
 [60] "Marginoferrorpercentvotedcitizen_35to44"
 [61] "Marginoferrorpercentvotedcitizen_45to64"
 [62] "Marginoferrorpercentvotedcitizen_65"
 [63] "Totalpopulation_Total"
 [64] "Totalpopulation_Male"
 [65] "Totalpopulation_Female"
 [66] "Totalpopulation_Whitealone"
 [67] "Totalpopulation_WhitenonHispanicalone"
 [68] "Totalpopulation_Blackalone"
 [69] "Totalpopulation_Asianalone"
 [70] "Totalpopulation_Hispanicofanyrace"
 [71] "Totalpopulation_Whitealoneorincombination"
 [72] "Totalpopulation_Blackaloneorincombination"
 [73] "Totalpopulation_Asianaloneorincombination"
 [74] "Totalcitizenpopulation_Total"
 [75] "Totalcitizenpopulation_Male"
 [76] "Totalcitizenpopulation_Female"
 [77] "Totalcitizenpopulation_Whitealone"
 [78] "Totalcitizenpopulation_WhitenonHispanicalone"
 [79] "Totalcitizenpopulation_Blackalone"
 [80] "Totalcitizenpopulation_Asianalone"
 [81] "Totalcitizenpopulation_Hispanicofanyrace"
 [82] "Totalcitizenpopulation_Whitealoneorincombination"
 [83] "Totalcitizenpopulation_Blackaloneorincombination"
 [84] "Totalcitizenpopulation_Asianaloneorincombination"
 [85] "Totalregistered_Total"
 [86] "Totalregistered_Male"
 [87] "Totalregistered_Female"
 [88] "Totalregistered_Whitealone"
 [89] "Totalregistered_WhitenonHispanicalone"
 [90] "Totalregistered_Blackalone"
 [91] "Totalregistered_Asianalone"
 [92] "Totalregistered_Hispanicofanyrace"
 [93] "Totalregistered_Whitealoneorincombination"
 [94] "Totalregistered_Blackaloneorincombination"
 [95] "Totalregistered_Asianaloneorincombination"
 [96] "PercentregisteredTotal_Total"
 [97] "PercentregisteredTotal_Male"
 [98] "PercentregisteredTotal_Female"
 [99] "PercentregisteredTotal_Whitealone"
[100] "PercentregisteredTotal_WhitenonHispanicalone"
[101] "PercentregisteredTotal_Blackalone"
[102] "PercentregisteredTotal_Asianalone"
[103] "PercentregisteredTotal_Hispanicofanyrace"
[104] "PercentregisteredTotal_Whitealoneorincombination"
[105] "PercentregisteredTotal_Blackaloneorincombination"
[106] "PercentregisteredTotal_Asianaloneorincombination"
[107] "Marginoferrorforpercentregisteredtotal_Total"
[108] "Marginoferrorforpercentregisteredtotal_Male"
[109] "Marginoferrorforpercentregisteredtotal_Female"
[110] "Marginoferrorforpercentregisteredtotal_Whitealone"
[111] "Marginoferrorforpercentregisteredtotal_WhitenonHispanicalone"
[112] "Marginoferrorforpercentregisteredtotal_Blackalone"
[113] "Marginoferrorforpercentregisteredtotal_Asianalone"
[114] "Marginoferrorforpercentregisteredtotal_Hispanicofanyrace"
[115] "Marginoferrorforpercentregisteredtotal_Whitealoneorincombination"
[116] "Marginoferrorforpercentregisteredtotal_Blackaloneorincombination"
[117] "Marginoferrorforpercentregisteredtotal_Asianaloneorincombination"
[118] "PercentregisteredCitizen_Total"
[119] "PercentregisteredCitizen_Male"
[120] "PercentregisteredCitizen_Female"
[121] "PercentregisteredCitizen_Whitealone"
[122] "PercentregisteredCitizen_WhitenonHispanicalone"
[123] "PercentregisteredCitizen_Blackalone"
[124] "PercentregisteredCitizen_Asianalone"
[125] "PercentregisteredCitizen_Hispanicofanyrace"
[126] "PercentregisteredCitizen_Whitealoneorincombination"
[127] "PercentregisteredCitizen_Blackaloneorincombination"
[128] "PercentregisteredCitizen_Asianaloneorincombination"
[129] "Marginoferrorforpercentregisteredcitizen_Total"
[130] "Marginoferrorforpercentregisteredcitizen_Male"
[131] "Marginoferrorforpercentregisteredcitizen_Female"
[132] "Marginoferrorforpercentregisteredcitizen_Whitealone"
[133] "Marginoferrorforpercentregisteredcitizen_WhitenonHispanicalone"
[134] "Marginoferrorforpercentregisteredcitizen_Blackalone"
[135] "Marginoferrorforpercentregisteredcitizen_Asianalone"
[136] "Marginoferrorforpercentregisteredcitizen_Hispanicofanyrace"
[137] "Marginoferrorforpercentregisteredcitizen_Whitealoneorincombination"
[138] "Marginoferrorforpercentregisteredcitizen_Blackaloneorincombination"
[139] "Marginoferrorforpercentregisteredcitizen_Asianaloneorincombination"
[140] "Totalvoted_Total"
[141] "Totalvoted_Male"
[142] "Totalvoted_Female"
[143] "Totalvoted_Whitealone"
[144] "Totalvoted_WhitenonHispanicalone"
[145] "Totalvoted_Blackalone"
[146] "Totalvoted_Asianalone"
[147] "Totalvoted_Hispanicofanyrace"
[148] "Totalvoted_Whitealoneorincombination"
[149] "Totalvoted_Blackaloneorincombination"
[150] "Totalvoted_Asianaloneorincombination"
[151] "PercentvotedTotal_Total"
[152] "PercentvotedTotal_Male"
[153] "PercentvotedTotal_Female"
[154] "PercentvotedTotal_Whitealone"
[155] "PercentvotedTotal_WhitenonHispanicalone"
[156] "PercentvotedTotal_Blackalone"
[157] "PercentvotedTotal_Asianalone"
[158] "PercentvotedTotal_Hispanicofanyrace"
[159] "PercentvotedTotal_Whitealoneorincombination"
[160] "PercentvotedTotal_Blackaloneorincombination"
[161] "PercentvotedTotal_Asianaloneorincombination"
[162] "Marginoferrorpercentvotedtotal_Total"
[163] "Marginoferrorpercentvotedtotal_Male"
[164] "Marginoferrorpercentvotedtotal_Female"
[165] "Marginoferrorpercentvotedtotal_Whitealone"
[166] "Marginoferrorpercentvotedtotal_WhitenonHispanicalone"
[167] "Marginoferrorpercentvotedtotal_Blackalone"
[168] "Marginoferrorpercentvotedtotal_Asianalone"
[169] "Marginoferrorpercentvotedtotal_Hispanicofanyrace"
[170] "Marginoferrorpercentvotedtotal_Whitealoneorincombination"
[171] "Marginoferrorpercentvotedtotal_Blackaloneorincombination"
[172] "Marginoferrorpercentvotedtotal_Asianaloneorincombination"
[173] "PercentvotedCitizen_Total"
[174] "PercentvotedCitizen_Male"
[175] "PercentvotedCitizen_Female"
[176] "PercentvotedCitizen_Whitealone"
[177] "PercentvotedCitizen_WhitenonHispanicalone"
[178] "PercentvotedCitizen_Blackalone"
[179] "PercentvotedCitizen_Asianalone"
[180] "PercentvotedCitizen_Hispanicofanyrace"
[181] "PercentvotedCitizen_Whitealoneorincombination"
[182] "PercentvotedCitizen_Blackaloneorincombination"
[183] "PercentvotedCitizen_Asianaloneorincombination"
[184] "Marginoferrorpercentvotedcitizen_Total"
[185] "Marginoferrorpercentvotedcitizen_Male"
[186] "Marginoferrorpercentvotedcitizen_Female"
[187] "Marginoferrorpercentvotedcitizen_Whitealone"
[188] "Marginoferrorpercentvotedcitizen_WhitenonHispanicalone"
[189] "Marginoferrorpercentvotedcitizen_Blackalone"
[190] "Marginoferrorpercentvotedcitizen_Asianalone"
[191] "Marginoferrorpercentvotedcitizen_Hispanicofanyrace"
[192] "Marginoferrorpercentvotedcitizen_Whitealoneorincombination"
[193] "Marginoferrorpercentvotedcitizen_Blackaloneorincombination"
[194] "Marginoferrorpercentvotedcitizen_Asianaloneorincombination"
[195] "Totalpopulation_25to44"
[196] "Totalpopulation_65to74"
[197] "Totalpopulation_75"
[198] "Totalcitizenpopulation_25to44"
[199] "Totalcitizenpopulation_65to74"
[200] "Totalcitizenpopulation_75"
[201] "Totalregistered_25to44"
[202] "Totalregistered_65to74"
[203] "Totalregistered_75"
[204] "PercentregisteredTotal_25to44"
[205] "PercentregisteredTotal_65to74"
[206] "PercentregisteredTotal_75"
[207] "Marginoferrorforpercentregisteredtotal_25to44"
[208] "Marginoferrorforpercentregisteredtotal_65to74"
[209] "Marginoferrorforpercentregisteredtotal_75"
[210] "PercentregisteredCitizen_25to44"
[211] "PercentregisteredCitizen_65to74"
[212] "PercentregisteredCitizen_75"
[213] "Marginoferrorforpercentregisteredcitizen_25to44"
[214] "Marginoferrorforpercentregisteredcitizen_65to74"
[215] "Marginoferrorforpercentregisteredcitizen_75"
[216] "Totalvoted_25to44"
[217] "Totalvoted_65to74"
[218] "Totalvoted_75"
[219] "PercentvotedTotal_25to44"
[220] "PercentvotedTotal_65to74"
[221] "PercentvotedTotal_75"
[222] "Marginoferrorpercentvotedtotal_25to44"
[223] "Marginoferrorpercentvotedtotal_65to74"
[224] "Marginoferrorpercentvotedtotal_75"
[225] "PercentvotedCitizen_25to44"
[226] "PercentvotedCitizen_65to74"
[227] "PercentvotedCitizen_75"
[228] "Marginoferrorpercentvotedcitizen_25to44"
[229] "Marginoferrorpercentvotedcitizen_65to74"
[230] "Marginoferrorpercentvotedcitizen_75"
[231] "Totalpopulation_45to54"
[232] "Totalpopulation_55to64"
[233] "Totalpopulation_18to44"
[234] "Totalcitizenpopulation_45to54"
[235] "Totalcitizenpopulation_55to64"
[236] "Totalcitizenpopulation_18to44"
[237] "Totalregistered_45to54"
[238] "Totalregistered_55to64"
[239] "Totalregistered_18to44"
[240] "PercentregisteredTotal_45to54"
[241] "PercentregisteredTotal_55to64"
[242] "PercentregisteredTotal_18to44"
[243] "Marginoferrorforpercentregisteredtotal_45to54"
[244] "Marginoferrorforpercentregisteredtotal_55to64"
[245] "Marginoferrorforpercentregisteredtotal_18to44"
[246] "PercentregisteredCitizen_45to54"
[247] "PercentregisteredCitizen_55to64"
[248] "PercentregisteredCitizen_18to44"
[249] "Marginoferrorforpercentregisteredcitizen_45to54"
[250] "Marginoferrorforpercentregisteredcitizen_55to64"
[251] "Marginoferrorforpercentregisteredcitizen_18to44"
[252] "Totalvoted_45to54"
[253] "Totalvoted_55to64"
[254] "Totalvoted_18to44"
[255] "PercentvotedTotal_45to54"
[256] "PercentvotedTotal_55to64"
[257] "PercentvotedTotal_18to44"
[258] "Marginoferrorpercentvotedtotal_45to54"
[259] "Marginoferrorpercentvotedtotal_55to64"
[260] "Marginoferrorpercentvotedtotal_18to44"
[261] "PercentvotedCitizen_45to54"
[262] "PercentvotedCitizen_55to64"
[263] "PercentvotedCitizen_18to44"
[264] "Marginoferrorpercentvotedcitizen_45to54"
[265] "Marginoferrorpercentvotedcitizen_55to64"
[266] "Marginoferrorpercentvotedcitizen_18to44"
[267] "PercentCitizenPopulation_18to24"
[268] "PercentCitizenPopulation_25to44"
[269] "PercentCitizenPopulation_45to64"
[270] "PercentCitizenPopulation_65to74"
[271] "PercentCitizenPopulation_75"
[272] "Marginoferrorpercentcitizen_18to24"
[273] "Marginoferrorpercentcitizen_25to44"
[274] "Marginoferrorpercentcitizen_45to64"
[275] "Marginoferrorpercentcitizen_65to74"
[276] "Marginoferrorpercentcitizen_75"
[277] "Totalpopulation_WhitenonHispanicaloneorincombination"
[278] "Totalpopulation_NonHispanicWhite"
[279] "Totalcitizenpopulation_WhitenonHispanicaloneorincombination"
[280] "Totalcitizenpopulation_NonHispanicWhite"
[281] "PercentCitizenPopulation_Total"
[282] "PercentCitizenPopulation_Male"
[283] "PercentCitizenPopulation_Female"
[284] "PercentCitizenPopulation_Whitealone"
[285] "PercentCitizenPopulation_WhitenonHispanicalone"
[286] "PercentCitizenPopulation_Blackalone"
[287] "PercentCitizenPopulation_Asianalone"
[288] "PercentCitizenPopulation_Hispanicofanyrace"
[289] "PercentCitizenPopulation_Whitealoneorincombination"
[290] "PercentCitizenPopulation_WhitenonHispanicaloneorincombination"
[291] "PercentCitizenPopulation_Blackaloneorincombination"
[292] "PercentCitizenPopulation_Asianaloneorincombination"
[293] "PercentCitizenPopulation_NonHispanicWhite"
[294] "Marginoferrorpercentcitizen_Total"
[295] "Marginoferrorpercentcitizen_Male"
[296] "Marginoferrorpercentcitizen_Female"
[297] "Marginoferrorpercentcitizen_Whitealone"
[298] "Marginoferrorpercentcitizen_WhitenonHispanicalone"
[299] "Marginoferrorpercentcitizen_Blackalone"
[300] "Marginoferrorpercentcitizen_Asianalone"
[301] "Marginoferrorpercentcitizen_Hispanicofanyrace"
[302] "Marginoferrorpercentcitizen_Whitealoneorincombination"
[303] "Marginoferrorpercentcitizen_WhitenonHispanicaloneorincombination"
[304] "Marginoferrorpercentcitizen_Blackaloneorincombination"
[305] "Marginoferrorpercentcitizen_Asianaloneorincombination"
[306] "Marginoferrorpercentcitizen_NonHispanicWhite"
[307] "Totalregistered_WhitenonHispanicaloneorincombination"
[308] "Totalregistered_NonHispanicWhite"
[309] "PercentregisteredTotal_WhitenonHispanicaloneorincombination"
[310] "PercentregisteredTotal_NonHispanicWhite"
[311] "Marginoferrorforpercentregisteredtotal_WhitenonHispanicaloneorincombination"
[312] "Marginoferrorforpercentregisteredtotal_NonHispanicWhite"
[313] "PercentregisteredCitizen_WhitenonHispanicaloneorincombination"
[314] "PercentregisteredCitizen_NonHispanicWhite"
[315] "Totalvoted_WhitenonHispanicaloneorincombination"
[316] "Totalvoted_NonHispanicWhite"
[317] "PercentvotedTotal_WhitenonHispanicaloneorincombination"
[318] "PercentvotedTotal_NonHispanicWhite"
[319] "Marginoferrorpercentvotedtotal_WhitenonHispanicaloneorincombination"
[320] "Marginoferrorpercentvotedtotal_NonHispanicWhite"
[321] "PercentvotedCitizen_WhitenonHispanicaloneorincombination"
[322] "PercentvotedCitizen_NonHispanicWhite"
[323] "Totalpopulation_NonHispanicBlack"
[324] "Totalcitizenpopulation_NonHispanicBlack"
[325] "PercentCitizenPopulation_NonHispanicBlack"
[326] "Marginoferrorpercentcitizen_NonHispanicBlack"
[327] "Totalregistered_NonHispanicBlack"
[328] "PercentregisteredTotal_NonHispanicBlack"
[329] "Marginoferrorforpercentregisteredtotal_NonHispanicBlack"
[330] "PercentregisteredCitizen_NonHispanicBlack"
[331] "Totalvoted_NonHispanicBlack"
[332] "PercentvotedTotal_NonHispanicBlack"
[333] "Marginoferrorpercentvotedtotal_NonHispanicBlack"
[334] "PercentvotedCitizen_NonHispanicBlack"

In [4]:
#Dropping the margin of error and percent citizen variables because they aren't needed for the analysis 
margin_columns <- grep("^Margin", names(final))
cit_columns <- grep("^PercentCitizenPopulation", names(final))

# Drop columns 
final <- final[, -c(margin_columns, cit_columns)]

In [5]:
head(final,20)

   STATE   Year Totalpopulation_18to24 Totalpopulation_25to34
1  ALABAMA 2000 430                     NA
2  ALABAMA 2002 396                     NA
3  ALABAMA 2004 413                     NA
4  ALABAMA 2006  NA                     NA
5  ALABAMA 2008 458                     NA
6  ALABAMA 2010 397                     NA
7  ALABAMA 2012 439                    576
8  ALABAMA 2014 482                    555
9  ALABAMA 2016 513                    583
10 ALABAMA 2018 458                    660
11 ALABAMA 2020 431                    599
12 ALASKA  2000  58                     NA
13 ALASKA  2002  56                     NA
14 ALASKA  2004  60                     NA
15 ALASKA  2006  NA                     NA
16 ALASKA  2008  NA                     NA
17 ALASKA  2010  66                     NA
18 ALASKA  2012  63                    109
19 ALASKA  2014  76                    111
20 ALASKA  2016  65                    113
   Totalpopulation_35to44 Totalpopulation_45to64 Totalpopulation_65
1   NA                    1063                    NA
2   NA                    1115                    NA
3   NA                    1131                    NA
4   NA                      NA                    NA
5   NA                    1210                    NA
6   NA                    1254                    NA
7  615                    1297                   667
8  610                    1298                   710
9  566                    1293                   761
10 556                    1340                   740
11 626                    1261                   852
12  NA                     144                    NA
13  NA                     162                    NA
14  NA                     166                    NA
15  NA                      NA                    NA
16  NA                     191                    44
17  NA                     182                    NA
18  86                     186                    72
19  78                     189                    66
20  83                     180                    77
   Totalcitizenpopulation_18to24 Totalcitizenpopulation_25to34
1  418                            NA
2  385                            NA
3  387                            NA
4   NA                            NA
5  441                            NA
6  388                            NA
7  428                           535
8  449                           519
9  497                           568
10 434                           619
11 427                           587
12  55                            NA
13  51                            NA
14  58                            NA
15  NA                            NA
16  NA                            NA
17  64                            NA
18  61                           103
19  74                           107
20  65                           109
   Totalcitizenpopulation_35to44 ⋯
1   NA                           ⋯
2   NA                           ⋯
3   NA                           ⋯
4   NA                           ⋯
5   NA                           ⋯
6   NA                           ⋯
7  582                           ⋯
8  566                           ⋯
9  548                           ⋯
10 508                           ⋯
11 608                           ⋯
12  NA                           ⋯
13  NA                           ⋯
14  NA                           ⋯
15  NA                           ⋯
16  NA                           ⋯
17  NA                           ⋯
18  80                           ⋯
19  75                           ⋯
20  79                           ⋯
   PercentvotedCitizen_WhitenonHispanicaloneorincombination
1        NA
2        NA
3  63.64389
4        NA
5        NA
6        NA
7        NA
8        NA
9        NA
10       NA
11       NA
12       NA
13       NA
14 71.30682
15       NA
16       NA
17       NA
18       NA
19       NA
20       NA
   PercentvotedCitizen_NonHispanicWhite Totalpopulation_NonHispanicBlack
1  61.35593                             853
2  51.70691                             776
3        NA                              NA
4        NA                              NA
5        NA                              NA
6        NA                              NA
7        NA                              NA
8        NA                              NA
9        NA                              NA
10       NA                              NA
11       NA                              NA
12 71.84466                              13
13 58.78594                              10
14       NA                              NA
15       NA                              NA
16       NA                              NA
17       NA                              NA
18       NA                              NA
19       NA                              NA
20       NA                              NA
   Totalcitizenpopulation_NonHispanicBlack Totalregistered_NonHispanicBlack
1  841                                     613
2  776                                     524
3   NA                                      NA
4   NA                                      NA
5   NA                                      NA
6   NA                                      NA
7   NA                                      NA
8   NA                                      NA
9   NA                                      NA
10  NA                                      NA
11  NA                                      NA
12  13                                       7
13  10                                       4
14  NA                                      NA
15  NA                                      NA
16  NA                                      NA
17  NA                                      NA
18  NA                                      NA
19  NA                                      NA
20  NA                                      NA
   PercentregisteredTotal_NonHispanicBlack
1  71.86401
2  67.52577
3        NA
4        NA
5        NA
6        NA
7        NA
8        NA
9        NA
10       NA
11       NA
12 53.84615
13 40.00000
14       NA
15       NA
16       NA
17       NA
18       NA
19       NA
20       NA
   PercentregisteredCitizen_NonHispanicBlack Totalvoted_NonHispanicBlack
1  72.88942                                  485
2  67.52577                                  336
3        NA                                   NA
4        NA                                   NA
5        NA                                   NA
6        NA                                   NA
7        NA                                   NA
8        NA                                   NA
9        NA                                   NA
10       NA                                   NA
11       NA                                   NA
12 53.84615                                    7
13 40.00000                                    3
14       NA                                   NA
15       NA                                   NA
16       NA                                   NA
17       NA                                   NA
18       NA                                   NA
19       NA                                   NA
20       NA                                   NA
   PercentvotedTotal_NonHispanicBlack PercentvotedCitizen_NonHispanicBlack
1  56.85815                           57.66944
2  43.29897                           43.29897
3        NA                                 NA
4        NA                                 NA
5        NA                                 NA
6        NA                                 NA
7        NA                                 NA
8        NA                                 NA
9        NA                                 NA
10       NA                                 NA
11       NA                                 NA
12 53.84615                           53.84615
13 30.00000                           30.00000
14       NA                                 NA
15       NA                                 NA
16       NA                                 NA
17       NA                                 NA
18       NA                                 NA
19       NA                                 NA
20       NA                                 NA

In [6]:
#Cleaning up the column names, shortening them 
totalpop_columns <- grep("^Totalpopulation", names(final))
totalcpop_columns <- grep("^Totalcitizenpopulation", names(final))
totalreg_columns <- grep("^Totalregistered", names(final))
totalvote_columns <- grep("^Totalvoted", names(final))
perreg_columns <- grep("^PercentregisteredTotal", names(final))
perregC_columns <- grep("^PercentregisteredCitizen", names(final))
pervote_columns <- grep("^PercentvotedTotal", names(final))
pervoteC_columns <- grep("^PercentvotedCitizen", names(final))


names(final)[totalpop_columns] <- gsub("^Totalpopulation", "TotPop", names(final)[totalpop_columns])
names(final)[totalcpop_columns] <- gsub("^Totalcitizenpopulation", "TotCPop", names(final)[totalcpop_columns])
names(final)[totalreg_columns] <- gsub("^Totalregistered", "TotReg", names(final)[totalreg_columns])
names(final)[totalvote_columns] <- gsub("^Totalvoted", "TotVote", names(final)[totalvote_columns])
names(final)[perreg_columns] <- gsub("^PercentregisteredTotal", "PRegT", names(final)[perreg_columns])
names(final)[perregC_columns] <- gsub("^PercentregisteredCitizen", "PRegC", names(final)[perregC_columns])
names(final)[pervote_columns] <- gsub("^PercentvotedTotal", "PVoteT", names(final)[pervote_columns])
names(final)[pervoteC_columns] <- gsub("^PercentvotedCitizen", "PVoteC", names(final)[pervoteC_columns])

In [7]:
#Checking that I did this correctly 
colnames(final)

  [1] "STATE"
  [2] "Year"
  [3] "TotPop_18to24"
  [4] "TotPop_25to34"
  [5] "TotPop_35to44"
  [6] "TotPop_45to64"
  [7] "TotPop_65"
  [8] "TotCPop_18to24"
  [9] "TotCPop_25to34"
 [10] "TotCPop_35to44"
 [11] "TotCPop_45to64"
 [12] "TotCPop_65"
 [13] "TotReg_18to24"
 [14] "TotReg_25to34"
 [15] "TotReg_35to44"
 [16] "TotReg_45to64"
 [17] "TotReg_65"
 [18] "PRegT_18to24"
 [19] "PRegT_25to34"
 [20] "PRegT_35to44"
 [21] "PRegT_45to64"
 [22] "PRegT_65"
 [23] "PRegC_18to24"
 [24] "PRegC_25to34"
 [25] "PRegC_35to44"
 [26] "PRegC_45to64"
 [27] "PRegC_65"
 [28] "TotVote_18to24"
 [29] "TotVote_25to34"
 [30] "TotVote_35to44"
 [31] "TotVote_45to64"
 [32] "TotVote_65"
 [33] "PVoteT_18to24"
 [34] "PVoteT_25to34"
 [35] "PVoteT_35to44"
 [36] "PVoteT_45to64"
 [37] "PVoteT_65"
 [38] "PVoteC_18to24"
 [39] "PVoteC_25to34"
 [40] "PVoteC_35to44"
 [41] "PVoteC_45to64"
 [42] "PVoteC_65"
 [43] "TotPop_Total"
 [44] "TotPop_Male"
 [45] "TotPop_Female"
 [46] "TotPop_Whitealone"
 [47] "TotPop_WhitenonHispanicalone"
 [48] "TotPop_Blackalone"
 [49] "TotPop_Asianalone"
 [50] "TotPop_Hispanicofanyrace"
 [51] "TotPop_Whitealoneorincombination"
 [52] "TotPop_Blackaloneorincombination"
 [53] "TotPop_Asianaloneorincombination"
 [54] "TotCPop_Total"
 [55] "TotCPop_Male"
 [56] "TotCPop_Female"
 [57] "TotCPop_Whitealone"
 [58] "TotCPop_WhitenonHispanicalone"
 [59] "TotCPop_Blackalone"
 [60] "TotCPop_Asianalone"
 [61] "TotCPop_Hispanicofanyrace"
 [62] "TotCPop_Whitealoneorincombination"
 [63] "TotCPop_Blackaloneorincombination"
 [64] "TotCPop_Asianaloneorincombination"
 [65] "TotReg_Total"
 [66] "TotReg_Male"
 [67] "TotReg_Female"
 [68] "TotReg_Whitealone"
 [69] "TotReg_WhitenonHispanicalone"
 [70] "TotReg_Blackalone"
 [71] "TotReg_Asianalone"
 [72] "TotReg_Hispanicofanyrace"
 [73] "TotReg_Whitealoneorincombination"
 [74] "TotReg_Blackaloneorincombination"
 [75] "TotReg_Asianaloneorincombination"
 [76] "PRegT_Total"
 [77] "PRegT_Male"
 [78] "PRegT_Female"
 [79] "PRegT_Whitealone"
 [80] "PRegT_WhitenonHispanicalone"
 [81] "PRegT_Blackalone"
 [82] "PRegT_Asianalone"
 [83] "PRegT_Hispanicofanyrace"
 [84] "PRegT_Whitealoneorincombination"
 [85] "PRegT_Blackaloneorincombination"
 [86] "PRegT_Asianaloneorincombination"
 [87] "PRegC_Total"
 [88] "PRegC_Male"
 [89] "PRegC_Female"
 [90] "PRegC_Whitealone"
 [91] "PRegC_WhitenonHispanicalone"
 [92] "PRegC_Blackalone"
 [93] "PRegC_Asianalone"
 [94] "PRegC_Hispanicofanyrace"
 [95] "PRegC_Whitealoneorincombination"
 [96] "PRegC_Blackaloneorincombination"
 [97] "PRegC_Asianaloneorincombination"
 [98] "TotVote_Total"
 [99] "TotVote_Male"
[100] "TotVote_Female"
[101] "TotVote_Whitealone"
[102] "TotVote_WhitenonHispanicalone"
[103] "TotVote_Blackalone"
[104] "TotVote_Asianalone"
[105] "TotVote_Hispanicofanyrace"
[106] "TotVote_Whitealoneorincombination"
[107] "TotVote_Blackaloneorincombination"
[108] "TotVote_Asianaloneorincombination"
[109] "PVoteT_Total"
[110] "PVoteT_Male"
[111] "PVoteT_Female"
[112] "PVoteT_Whitealone"
[113] "PVoteT_WhitenonHispanicalone"
[114] "PVoteT_Blackalone"
[115] "PVoteT_Asianalone"
[116] "PVoteT_Hispanicofanyrace"
[117] "PVoteT_Whitealoneorincombination"
[118] "PVoteT_Blackaloneorincombination"
[119] "PVoteT_Asianaloneorincombination"
[120] "PVoteC_Total"
[121] "PVoteC_Male"
[122] "PVoteC_Female"
[123] "PVoteC_Whitealone"
[124] "PVoteC_WhitenonHispanicalone"
[125] "PVoteC_Blackalone"
[126] "PVoteC_Asianalone"
[127] "PVoteC_Hispanicofanyrace"
[128] "PVoteC_Whitealoneorincombination"
[129] "PVoteC_Blackaloneorincombination"
[130] "PVoteC_Asianaloneorincombination"
[131] "TotPop_25to44"
[132] "TotPop_65to74"
[133] "TotPop_75"
[134] "TotCPop_25to44"
[135] "TotCPop_65to74"
[136] "TotCPop_75"
[137] "TotReg_25to44"
[138] "TotReg_65to74"
[139] "TotReg_75"
[140] "PRegT_25to44"
[141] "PRegT_65to74"
[142] "PRegT_75"
[143] "PRegC_25to44"
[144] "PRegC_65to74"
[145] "PRegC_75"
[146] "TotVote_25to44"
[147] "TotVote_65to74"
[148] "TotVote_75"
[149] "PVoteT_25to44"
[150] "PVoteT_65to74"
[151] "PVoteT_75"
[152] "PVoteC_25to44"
[153] "PVoteC_65to74"
[154] "PVoteC_75"
[155] "TotPop_45to54"
[156] "TotPop_55to64"
[157] "TotPop_18to44"
[158] "TotCPop_45to54"
[159] "TotCPop_55to64"
[160] "TotCPop_18to44"
[161] "TotReg_45to54"
[162] "TotReg_55to64"
[163] "TotReg_18to44"
[164] "PRegT_45to54"
[165] "PRegT_55to64"
[166] "PRegT_18to44"
[167] "PRegC_45to54"
[168] "PRegC_55to64"
[169] "PRegC_18to44"
[170] "TotVote_45to54"
[171] "TotVote_55to64"
[172] "TotVote_18to44"
[173] "PVoteT_45to54"
[174] "PVoteT_55to64"
[175] "PVoteT_18to44"
[176] "PVoteC_45to54"
[177] "PVoteC_55to64"
[178] "PVoteC_18to44"
[179] "TotPop_WhitenonHispanicaloneorincombination"
[180] "TotPop_NonHispanicWhite"
[181] "TotCPop_WhitenonHispanicaloneorincombination"
[182] "TotCPop_NonHispanicWhite"
[183] "TotReg_WhitenonHispanicaloneorincombination"
[184] "TotReg_NonHispanicWhite"
[185] "PRegT_WhitenonHispanicaloneorincombination"
[186] "PRegT_NonHispanicWhite"
[187] "PRegC_WhitenonHispanicaloneorincombination"
[188] "PRegC_NonHispanicWhite"
[189] "TotVote_WhitenonHispanicaloneorincombination"
[190] "TotVote_NonHispanicWhite"
[191] "PVoteT_WhitenonHispanicaloneorincombination"
[192] "PVoteT_NonHispanicWhite"
[193] "PVoteC_WhitenonHispanicaloneorincombination"
[194] "PVoteC_NonHispanicWhite"
[195] "TotPop_NonHispanicBlack"
[196] "TotCPop_NonHispanicBlack"
[197] "TotReg_NonHispanicBlack"
[198] "PRegT_NonHispanicBlack"
[199] "PRegC_NonHispanicBlack"
[200] "TotVote_NonHispanicBlack"
[201] "PVoteT_NonHispanicBlack"
[202] "PVoteC_NonHispanicBlack"

In [8]:
#Creating variable for difference in black and white voting rates
final$Dif_WhiteBlack <- ifelse(is.na(final$PVoteC_Whitealoneorincombination) | is.na(final$PVoteC_Blackaloneorincombination),
                            NA, 
                            final$PVoteC_Whitealoneorincombination - final$PVoteC_Blackaloneorincombination)

In [9]:
#Creating variable for difference in black and white voting rates
final$Dif_45to64_18to24 <- ifelse(is.na(final$PVoteC_45to64) | is.na(final$PVoteC_18to24),
                            NA, 
                            final$PVoteC_45to64 - final$PVoteC_18to24)

In [10]:
head(final)

  STATE   Year TotPop_18to24 TotPop_25to34 TotPop_35to44 TotPop_45to64
1 ALABAMA 2000 430           NA            NA            1063
2 ALABAMA 2002 396           NA            NA            1115
3 ALABAMA 2004 413           NA            NA            1131
4 ALABAMA 2006  NA           NA            NA              NA
5 ALABAMA 2008 458           NA            NA            1210
6 ALABAMA 2010 397           NA            NA            1254
  TotPop_65 TotCPop_18to24 TotCPop_25to34 TotCPop_35to44 ⋯
1 NA        418            NA             NA             ⋯
2 NA        385            NA             NA             ⋯
3 NA        387            NA             NA             ⋯
4 NA         NA            NA             NA             ⋯
5 NA        441            NA             NA             ⋯
6 NA        388            NA             NA             ⋯
  TotPop_NonHispanicBlack TotCPop_NonHispanicBlack TotReg_NonHispanicBlack
1 853                     841                      613
2 776                     776                      524
3  NA                      NA                       NA
4  NA                      NA                       NA
5  NA                      NA                       NA
6  NA                      NA                       NA
  PRegT_NonHispanicBlack PRegC_NonHispanicBlack TotVote_NonHispanicBlack
1 71.86401               72.88942               485
2 67.52577               67.52577               336
3       NA                     NA                NA
4       NA                     NA                NA
5       NA                     NA                NA
6       NA                     NA                NA
  PVoteT_NonHispanicBlack PVoteC_NonHispanicBlack Dif_WhiteBlack
1 56.85815                57.66944                 3.2701918
2 43.29897                43.29897                 8.0445613
3       NA                      NA                -0.6538216
4       NA                      NA                 2.9574854
5       NA                      NA                -0.1285376
6       NA                      NA                -3.0860191
  Dif_45to64_18to24
1 26.19119
2 30.00469
3 26.39439
4       NA
5 13.22444
6 33.72021

# Adding dummy variables

## Treatment and Year Dummies

In [11]:
preclearance <- c("ALABAMA", "ALASKA", "ARIZONA", "GEORGIA", "LOUISIANA", "MISSISSIPPI", "SOUTH CAROLINA", "TEXAS", "VIRGINIA")

semi_preclearance <- c("NORTH CAROLINA", "NEW YORK", "FLORIDA", "MICHIGAN", "CALIFORNIA", "SOUTH DAKOTA")

exclude <- c("US", "UNITED STATES")


all_states <- c("ALABAMA", "ALASKA", "ARIZONA", "ARKANSAS", "CALIFORNIA", "COLORADO", "CONNECTICUT", "DELAWARE", 
                "DISTRICT OF COLUMBIA", "FLORIDA", "GEORGIA", "HAWAII", "IDAHO", "ILLINOIS", "INDIANA", "IOWA", 
                "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", "MARYLAND", "MASSACHUSETTS", "MICHIGAN", "MINNESOTA", 
                "MISSISSIPPI", "MISSOURI", "MONTANA", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", 
                "NEW YORK", "NORTH CAROLINA", "NORTH DAKOTA", "OHIO", "OKLAHOMA", "OREGON", "PENNSYLVANIA", "RHODE ISLAND", 
                "SOUTH CAROLINA", "SOUTH DAKOTA", "TENNESSEE", "TEXAS", "UTAH", "VERMONT", "VIRGINIA",
                "WASHINGTON", "WEST VIRGINIA", "WISCONSIN", "WYOMING")

In [12]:
#Deleting terriroties to exclude
final <- final[!(final$STATE %in% exclude), ]

In [13]:
control <- setdiff(all_states, c(preclearance, semi_preclearance, exclude))

In [14]:
#Checking the size of the groups
length(control)
length(preclearance)
length(semi_preclearance)

[1] 36

[1] 9

[1] 6

In [15]:
# Create Treatment column
final$Treatment <- ifelse(final$STATE %in% c(preclearance), 1, 0)

In [16]:
# Create Semi-treatment columns
final$Semi_treatment <- ifelse(final$STATE %in% c(semi_preclearance), 1, 0)

In [17]:
head(final, 20)

   STATE   Year TotPop_18to24 TotPop_25to34 TotPop_35to44 TotPop_45to64
1  ALABAMA 2000 430            NA            NA           1063
2  ALABAMA 2002 396            NA            NA           1115
3  ALABAMA 2004 413            NA            NA           1131
4  ALABAMA 2006  NA            NA            NA             NA
5  ALABAMA 2008 458            NA            NA           1210
6  ALABAMA 2010 397            NA            NA           1254
7  ALABAMA 2012 439           576           615           1297
8  ALABAMA 2014 482           555           610           1298
9  ALABAMA 2016 513           583           566           1293
10 ALABAMA 2018 458           660           556           1340
11 ALABAMA 2020 431           599           626           1261
12 ALASKA  2000  58            NA            NA            144
13 ALASKA  2002  56            NA            NA            162
14 ALASKA  2004  60            NA            NA            166
15 ALASKA  2006  NA            NA            NA             NA
16 ALASKA  2008  NA            NA            NA            191
17 ALASKA  2010  66            NA            NA            182
18 ALASKA  2012  63           109            86            186
19 ALASKA  2014  76           111            78            189
20 ALASKA  2016  65           113            83            180
   TotPop_65 TotCPop_18to24 TotCPop_25to34 TotCPop_35to44 ⋯
1   NA       418             NA             NA            ⋯
2   NA       385             NA             NA            ⋯
3   NA       387             NA             NA            ⋯
4   NA        NA             NA             NA            ⋯
5   NA       441             NA             NA            ⋯
6   NA       388             NA             NA            ⋯
7  667       428            535            582            ⋯
8  710       449            519            566            ⋯
9  761       497            568            548            ⋯
10 740       434            619            508            ⋯
11 852       427            587            608            ⋯
12  NA        55             NA             NA            ⋯
13  NA        51             NA             NA            ⋯
14  NA        58             NA             NA            ⋯
15  NA        NA             NA             NA            ⋯
16  44        NA             NA             NA            ⋯
17  NA        64             NA             NA            ⋯
18  72        61            103             80            ⋯
19  66        74            107             75            ⋯
20  77        65            109             79            ⋯
   TotReg_NonHispanicBlack PRegT_NonHispanicBlack PRegC_NonHispanicBlack
1  613                     71.86401               72.88942
2  524                     67.52577               67.52577
3   NA                           NA                     NA
4   NA                           NA                     NA
5   NA                           NA                     NA
6   NA                           NA                     NA
7   NA                           NA                     NA
8   NA                           NA                     NA
9   NA                           NA                     NA
10  NA                           NA                     NA
11  NA                           NA                     NA
12   7                     53.84615               53.84615
13   4                     40.00000               40.00000
14  NA                           NA                     NA
15  NA                           NA                     NA
16  NA                           NA                     NA
17  NA                           NA                     NA
18  NA                           NA                     NA
19  NA                           NA                     NA
20  NA                           NA                     NA
   TotVote_NonHispanicBlack PVoteT_NonHispanicBlack PVoteC_NonHispanicBlack
1  485                      56.85815                57.66944
2  336                      43.29897                43.29897
3   NA                            NA                      NA
4   NA                            NA                      NA
5   NA                            NA                      NA
6   NA                            NA                      NA
7   NA                            NA                      NA
8   NA                            NA                      NA
9   NA                            NA                      NA
10  NA                            NA                      NA
11  NA                            NA                      NA
12   7                      53.84615                53.84615
13   3                      30.00000                30.00000
14  NA                            NA                      NA
15  NA                            NA                      NA
16  NA                            NA                      NA
17  NA                            NA                      NA
18  NA                            NA                      NA
19  NA                            NA                      NA
20  NA                            NA                      NA
   Dif_WhiteBlack Dif_45to64_18to24 Treatment Semi_treatment
1   3.2701918     26.19119          1         0
2   8.0445613     30.00469          1         0
3  -0.6538216     26.39439          1         0
4   2.9574854           NA          1         0
5  -0.1285376     13.22444          1         0
6  -3.0860191     33.72021          1         0
7  -1.8586777     37.43211          1         0
8  -3.1160103     32.18516          1         0
9  -3.8272550     16.79719          1         0
10  1.9787003     26.10092          1         0
11  7.7759794     20.69837          1         0
12 17.3137208     26.17666          1         0
13 31.1888112     43.88660          1         0
14  6.2864928     21.39835          1         0
15 17.0291777           NA          1         0
16 25.5555556           NA          1         0
17 19.5373419     43.82945          1         0
18 31.1920223     34.24608          1         0
19 16.0000000     35.73737          1         0
20 22.7166773     30.11494          1         0

In [18]:
pre_2013 <- c(2000,2002,2004,2006,2008,2010,2012)
post_2013 <- c(2014,2016,2018,2020)

In [19]:
# Create Year Post and Pre columns
final$pre_2013 <- ifelse(final$Year %in% c(pre_2013), 1, 0)
final$post_2013 <- ifelse(final$Year %in% c(post_2013), 1, 0)
final$is_2000 <- ifelse(final$Year==2000, 1, 0)
final$is_2002 <- ifelse(final$Year==2002, 1, 0)
final$is_2004 <- ifelse(final$Year==2004, 1, 0)
final$is_2006 <- ifelse(final$Year==2006, 1, 0)
final$is_2008 <- ifelse(final$Year==2008, 1, 0)
final$is_2010 <- ifelse(final$Year==2010, 1, 0)
final$is_2012 <- ifelse(final$Year==2012, 1, 0)
final$is_2014 <- ifelse(final$Year==2014, 1, 0)
final$is_2016 <- ifelse(final$Year==2016, 1, 0)
final$is_2018 <- ifelse(final$Year==2018, 1, 0)
final$is_2020 <- ifelse(final$Year==2020, 1, 0)

In [20]:
head(final, 20)

   STATE   Year TotPop_18to24 TotPop_25to34 TotPop_35to44 TotPop_45to64
1  ALABAMA 2000 430            NA            NA           1063
2  ALABAMA 2002 396            NA            NA           1115
3  ALABAMA 2004 413            NA            NA           1131
4  ALABAMA 2006  NA            NA            NA             NA
5  ALABAMA 2008 458            NA            NA           1210
6  ALABAMA 2010 397            NA            NA           1254
7  ALABAMA 2012 439           576           615           1297
8  ALABAMA 2014 482           555           610           1298
9  ALABAMA 2016 513           583           566           1293
10 ALABAMA 2018 458           660           556           1340
11 ALABAMA 2020 431           599           626           1261
12 ALASKA  2000  58            NA            NA            144
13 ALASKA  2002  56            NA            NA            162
14 ALASKA  2004  60            NA            NA            166
15 ALASKA  2006  NA            NA            NA             NA
16 ALASKA  2008  NA            NA            NA            191
17 ALASKA  2010  66            NA            NA            182
18 ALASKA  2012  63           109            86            186
19 ALASKA  2014  76           111            78            189
20 ALASKA  2016  65           113            83            180
   TotPop_65 TotCPop_18to24 TotCPop_25to34 TotCPop_35to44 ⋯ is_2002 is_2004
1   NA       418             NA             NA            ⋯ 0       0
2   NA       385             NA             NA            ⋯ 1       0
3   NA       387             NA             NA            ⋯ 0       1
4   NA        NA             NA             NA            ⋯ 0       0
5   NA       441             NA             NA            ⋯ 0       0
6   NA       388             NA             NA            ⋯ 0       0
7  667       428            535            582            ⋯ 0       0
8  710       449            519            566            ⋯ 0       0
9  761       497            568            548            ⋯ 0       0
10 740       434            619            508            ⋯ 0       0
11 852       427            587            608            ⋯ 0       0
12  NA        55             NA             NA            ⋯ 0       0
13  NA        51             NA             NA            ⋯ 1       0
14  NA        58             NA             NA            ⋯ 0       1
15  NA        NA             NA             NA            ⋯ 0       0
16  44        NA             NA             NA            ⋯ 0       0
17  NA        64             NA             NA            ⋯ 0       0
18  72        61            103             80            ⋯ 0       0
19  66        74            107             75            ⋯ 0       0
20  77        65            109             79            ⋯ 0       0
   is_2006 is_2008 is_2010 is_2012 is_2014 is_2016 is_2018 is_2020
1  0       0       0       0       0       0       0       0
2  0       0       0       0       0       0       0       0
3  0       0       0       0       0       0       0       0
4  1       0       0       0       0       0       0       0
5  0       1       0       0       0       0       0       0
6  0       0       1       0       0       0       0       0
7  0       0       0       1       0       0       0       0
8  0       0       0       0       1       0       0       0
9  0       0       0       0       0       1       0       0
10 0       0       0       0       0       0       1       0
11 0       0       0       0       0       0       0       1
12 0       0       0       0       0       0       0       0
13 0       0       0       0       0       0       0       0
14 0       0       0       0       0       0       0       0
15 1       0       0       0       0       0       0       0
16 0       1       0       0       0       0       0       0
17 0       0       1       0       0       0       0       0
18 0       0       0       1       0       0       0       0
19 0       0       0       0       1       0       0       0
20 0       0       0       0       0       1       0       0

## Presidential and Senate Race Years

In [21]:
#Creating presidential year column
pres_year <- c(2000,2004,2008,2012,2016,2020)
final$pres_year <- ifelse(final$Year %in% c(pres_year), 1, 0)

In [22]:
head(final, 20)

   STATE   Year TotPop_18to24 TotPop_25to34 TotPop_35to44 TotPop_45to64
1  ALABAMA 2000 430            NA            NA           1063
2  ALABAMA 2002 396            NA            NA           1115
3  ALABAMA 2004 413            NA            NA           1131
4  ALABAMA 2006  NA            NA            NA             NA
5  ALABAMA 2008 458            NA            NA           1210
6  ALABAMA 2010 397            NA            NA           1254
7  ALABAMA 2012 439           576           615           1297
8  ALABAMA 2014 482           555           610           1298
9  ALABAMA 2016 513           583           566           1293
10 ALABAMA 2018 458           660           556           1340
11 ALABAMA 2020 431           599           626           1261
12 ALASKA  2000  58            NA            NA            144
13 ALASKA  2002  56            NA            NA            162
14 ALASKA  2004  60            NA            NA            166
15 ALASKA  2006  NA            NA            NA             NA
16 ALASKA  2008  NA            NA            NA            191
17 ALASKA  2010  66            NA            NA            182
18 ALASKA  2012  63           109            86            186
19 ALASKA  2014  76           111            78            189
20 ALASKA  2016  65           113            83            180
   TotPop_65 TotCPop_18to24 TotCPop_25to34 TotCPop_35to44 ⋯ is_2004 is_2006
1   NA       418             NA             NA            ⋯ 0       0
2   NA       385             NA             NA            ⋯ 0       0
3   NA       387             NA             NA            ⋯ 1       0
4   NA        NA             NA             NA            ⋯ 0       1
5   NA       441             NA             NA            ⋯ 0       0
6   NA       388             NA             NA            ⋯ 0       0
7  667       428            535            582            ⋯ 0       0
8  710       449            519            566            ⋯ 0       0
9  761       497            568            548            ⋯ 0       0
10 740       434            619            508            ⋯ 0       0
11 852       427            587            608            ⋯ 0       0
12  NA        55             NA             NA            ⋯ 0       0
13  NA        51             NA             NA            ⋯ 0       0
14  NA        58             NA             NA            ⋯ 1       0
15  NA        NA             NA             NA            ⋯ 0       1
16  44        NA             NA             NA            ⋯ 0       0
17  NA        64             NA             NA            ⋯ 0       0
18  72        61            103             80            ⋯ 0       0
19  66        74            107             75            ⋯ 0       0
20  77        65            109             79            ⋯ 0       0
   is_2008 is_2010 is_2012 is_2014 is_2016 is_2018 is_2020 pres_year
1  0       0       0       0       0       0       0       1
2  0       0       0       0       0       0       0       0
3  0       0       0       0       0       0       0       1
4  0       0       0       0       0       0       0       0
5  1       0       0       0       0       0       0       1
6  0       1       0       0       0       0       0       0
7  0       0       1       0       0       0       0       1
8  0       0       0       1       0       0       0       0
9  0       0       0       0       1       0       0       1
10 0       0       0       0       0       1       0       0
11 0       0       0       0       0       0       1       1
12 0       0       0       0       0       0       0       1
13 0       0       0       0       0       0       0       0
14 0       0       0       0       0       0       0       1
15 0       0       0       0       0       0       0       0
16 1       0       0       0       0       0       0       1
17 0       1       0       0       0       0       0       0
18 0       0       1       0       0       0       0       1
19 0       0       0       1       0       0       0       0
20 0       0       0       0       1       0       0       1

In [23]:
#MAKING SENATE ELECTION DUMMIES

In [24]:
senate_2000 <- c("NEW JERSEY", "NEVADA", "NEBRASKA", "MASSACHUSETTS", "MARYLAND", "HAWAII", "GEORGIA", "CONNETICUT",
                "CALIFORNIA", "NEW MEXICO", "NEW YORK", "NORTH DAKOTA", "VIRGINIA", "WEST VIRGINIA", "WISCONSIN",
                "WYOMING", "WASHINGTON", "VERMONT", "UTAH", "TEXAS", "TENNESSEE", "RHODE ISLAND", "PENNSYLVANIA",
                "OHIO", "MONTANA", "MISSOURI", "MISSISSIPPI", "MINNESOTA", "MICHIGAN", "MAINE", "INDIANA", 
                "FLORIDA", "DELEWARE", "ARIZONA")

In [25]:
senate_2002 <- c("IOWA", "ILLINOIS", "GEORGIA", "DELEWARE", "LOUSIANA", "MASSACHUSETTS", "MICHIGAN", "MISSOURI",
                "MONTANA", "NEW JERSEY", "RHODE ISLAND", "SOUTH DAKOTA", "WEST VIRGINIA", "NEW MEXICO",
                "NORTH CAROLINA", "OKLAMHOMA", "OREGON", "SOUTH CAROLINA", "TENNESSEE", "TEXAS", "VIRGINIA", "WYOMING", 
                "MINNESOTA", "NEW HAMPSHIRE", "NEBRASKA", "MISSISSIPPI", "MAINE", "KENTUCKY", "KANSAS", "IDAHO",
                "COLORADO", "ARKANSAS", "ALASKA", "ALABAMA")

In [26]:
senate_2004 <- c("ARKANSAS", "NEW YORK", "NEVADA", "MARYLAND", "LOUSIANA", "INDIANA", "HAWAII", "GEORGIA", "FLORIDA",
                "CONNETICUT", "CALIFORNIA", "NORTH CAROLINA", "NORTH DAKOTA", "OREGON", "SOUTH CAROLINA", 
                "SOUTH DAKOTA", "VERMONT", "WASHINGTON", "WISCONSIN", "UTAH", "PENNSYLVANIA", "OKLAHOMA", 
                "OHIO", "NEW HAMPSHIRE", "MISSOURI", "KENTUCKY", "KANSAS", "IOWA", "ILLINOIS", "IDAHO",
                "COLORADO", "ARIZONA", "ALASKA", "ALABAMA")

In [27]:
senate_2006 <- c("CALIFORNIA", "CONNETICUT", "DELEWARE", "FLORIDA", "HAWAII", "MARYLAND", "MASSACHUSETTS", "MICHIGAN",
                "MINNESOTA", "NEBRASKA", "NEW JERSEY", "NEW MEXICO", "NEW YORK", "NORTH DAKOTA", "WASHINGTON",
                "WEST VIRGINIA", "WISCONSIN", "VERMONT", "WYOMING", "VIRGINIA", "UTAH", "TEXAS", "TENNESSEE",
                "RHODE ISLAND", "PENNSYLVANIA", "OHIO", "NEVADA", "MONTANA", "MISSOURI", "MISSISSIPPI", "MAINE",
                "INDIANA", "ARIZONA")

In [28]:
senate_2008 <- c("ILLINOIS", "DELEWARE", "ARKANSAS", "IOWA", "LOUSIANA", "MASSACHUSETTS", "MICHIGAN", "MONTANA", 
                "NEW JERSEY", "RHODE ISLAND", "SOUTH DAKOTA", "WEST VIRGINIA", "ALASKA", "COLORADO", "NEW HAMPSHIRE", 
                "NEW MEXICO", "NORTH CAROLINA", "OREGON", "VIRGINIA", "WYOMING", "TEXAS", "TENNESSEE", 
                "SOUTH CAROLINA", "OKLAHOMA", "NEBRASKA", "MISSISSIPPI", "MAINE", "KENTUCKY", "KANSAS", "IDAHO",
                "GEORGIA")

In [29]:
senate_2010 <- c("CALIFORNIA", "ARKANSAS", "COLORADO", "CONNETICUT", "DELEWARE", "HAWAII", "ILLINOIS", "INDIANA",
                "MARYLAND", "NEVADA", "NEW YORK", "NORTH DAKOTA", "OREGON", "PENNSYLVANIA", "VERMONT", "WASHINGTON", 
                "WEST VIRGINIA", "WISCONSIN", "UTAH", "SOUTH DAKOTA", "SOUTH CAROLINA", "OKLAHOMA", "OHIO", 
                "NORTH CAROLINA", "NEW HAMPSHIRE", "MISSSOURI", "LOUSIANA", "KENTUCKY", "KANSAS", "IOWA", "IDAHO", 
                "GEORGIA", "FLORIDA", "ARIZONA", "ALASKA", "ALABAMA")

In [30]:
senate_2012 <- c("NEBRASKA", "MONTANA", "MISSOURI", "MINNESOTA", "MICHIGAN", "MARYLAND", "HAWAII", "FLORIDA", 
                "DELEWARE", "CALIFORNIA", "WEST VIRGINIA", "WASHINGTON", "VIRGINIA", "RHODE ISLAND", "PENNSYLVANIA",
                "OHIO", "NORTH DAKOTA", "NEW YORK", "NEW MEXICO", "NEW JERSEY", "MASSACHUSETTS", "MISSISSIPPI", 
                "NEVADA", "TENNESSEE", "TEXAS", "UTAH", "WYOMING", "VERMONT", "CONNETICUT", "WISCONSIN",
                "MAINE", "INDIANA", "ARIZONA")

In [31]:
senate_2014 <- c("LOUISIANA", "IOWA", "ILLINOIS", "HAWAII", "DELEWARE", "COLORADO", "ARKANSAS", "ALASKA", "MASSACHUSETTS", 
                "MICHIGAN", "MINNESOTA", "MONTANA", "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", "NORTH CAROLINA", 
                "OREGON", "RHODE ISLAND", "SOUTH DAKOTA", "VIRGINA", "WEST VIRGINIA", "WYOMING", "TEXAS", "TENNESSEE", 
                "SOUTH CAROLINA", "OKLAHOMA", "NEBRASKA", "MISSISSIPPI", "MAINE", "KENTUCKY", "KANSAS", "IDAHO", "GEORGIA",
                "ALABAMA")

In [32]:
senate_2016 <- c("NEVADA", "MARYLAND", "HAWAII", "CONNETICUT", "COLORADO", "CALIFORNIA", "NEW YORK", "OREGON", "VERNOMT", 
                "WASHINGTON", "WISCONSIN", "UTAH", "SOUTH DAKOTA", "SOUTH CAROLINA", "PENNSYLVANIA", "OKLAHOMA", "OHIO", 
                "NORTH DAKOTA", "NORTH CAROLINA", "NEW HAMPSHIRE", "MISSOURI", "LOUISIANA", "KENTUCKY", "KANSAS", 
                "IOWA", "INDIANA", "ILLINOIS", "IDAHO", "GEORGIA", "FLORIDA", "ARKANSAS", "ARIZONA", "ALASKA", "ALABAMA")

In [33]:
senate_2018 <- c("ALABAMA", "CALIFORNIA", "CONNETICUT", "DELEWARE", "FLORIDA", "HAWAII", "INDIANA", "MARYLAND", 
                "MASSACHUSETTS", "MICHIGAN", "MINNESOTA", "MISSOURI", "MONTANA", "NEW JERSEY", "NEW MEXICO", "NEW YORK", 
                "NORTH DAKOTA", "OHIO", "PENNSYLVANIA", "RHODE ISLAND", "VIRGINIA", "WASHINGTON", "WEST VIRGINIA", 
                "WISCONSIN", "MAINE", "VERMONT", "WYOMING", "UTAH", "TEXAS", "TENNESSEE", "NEVADA", "NEBRASKA", 
                "MISSISSIPPI", "ARIZONA")

In [34]:
senate_2020 <- c("NEW HAMPSHIRE", "MINNESOTA", "MICHIGAN", "MASSACHUSETTS", "ILLINOIS", "DELEWARE", "ALABAMA", 
                "NEW JERSEY", "NEW MEXICO", "OREGON", "RHODE ISLAND", "VIRGINIA", "WYOMING", "WEST VIRGINIA", 
                "TEXAS", "TENNESSEE", "SOUTH DAKOTA", "SOUTH CAROLINA", "OKLAHOMA", "NORTH CAROLINA", "NEBRASKA",
                "MONTANA", "MISSISSIPPI", "MAINE", "LOUISIANA", "KENTUCKY", "KANSAS", "IOWA", "IDAHO", "GEORGIA",
                "COLORADO", "ARKANSAS", "ARIZONA", "ALASKA")

In [35]:
senate_2000 <- unique(senate_2000)
senate_2002 <- unique(senate_2002)
senate_2004 <- unique(senate_2004)
senate_2006 <- unique(senate_2006)
senate_2008 <- unique(senate_2008)
senate_2010 <- unique(senate_2010)
senate_2012 <- unique(senate_2012)
senate_2014 <- unique(senate_2014)
senate_2016 <- unique(senate_2016)
senate_2018 <- unique(senate_2018)
senate_2020 <- unique(senate_2020)

In [36]:
head(final)

  STATE   Year TotPop_18to24 TotPop_25to34 TotPop_35to44 TotPop_45to64
1 ALABAMA 2000 430           NA            NA            1063
2 ALABAMA 2002 396           NA            NA            1115
3 ALABAMA 2004 413           NA            NA            1131
4 ALABAMA 2006  NA           NA            NA              NA
5 ALABAMA 2008 458           NA            NA            1210
6 ALABAMA 2010 397           NA            NA            1254
  TotPop_65 TotCPop_18to24 TotCPop_25to34 TotCPop_35to44 ⋯ is_2004 is_2006
1 NA        418            NA             NA             ⋯ 0       0
2 NA        385            NA             NA             ⋯ 0       0
3 NA        387            NA             NA             ⋯ 1       0
4 NA         NA            NA             NA             ⋯ 0       1
5 NA        441            NA             NA             ⋯ 0       0
6 NA        388            NA             NA             ⋯ 0       0
  is_2008 is_2010 is_2012 is_2014 is_2016 is_2018 is_2020 pres_year
1 0       0       0       0       0       0       0       1
2 0       0       0       0       0       0       0       0
3 0       0       0       0       0       0       0       1
4 0       0       0       0       0       0       0       0
5 1       0       0       0       0       0       0       1
6 0       1       0       0       0       0       0       0

In [37]:
# Determine if there was a senate election in a given state in a given year
senate_values <- numeric(nrow(final))

# Iterate over each year from 2000 to 2020
for (year in seq(2000, 2020, by = 2)) {
  # Get the Senate vector for the current year
  senate_vector <- get(paste0("senate_", year))
  # Iterate over each row of the final data frame
  for (i in 1:nrow(final)) {
    if (final$STATE[i] %in% senate_vector & final$Year[i]==year) {
      # If present, set the corresponding element in senate_values to 1
      senate_values[i] <- 1
    }
  }
}

# Assign the senate_values vector to the senate column in the final data frame
final$senate <- senate_values

In [38]:
head(final, 20)

   STATE   Year TotPop_18to24 TotPop_25to34 TotPop_35to44 TotPop_45to64
1  ALABAMA 2000 430            NA            NA           1063
2  ALABAMA 2002 396            NA            NA           1115
3  ALABAMA 2004 413            NA            NA           1131
4  ALABAMA 2006  NA            NA            NA             NA
5  ALABAMA 2008 458            NA            NA           1210
6  ALABAMA 2010 397            NA            NA           1254
7  ALABAMA 2012 439           576           615           1297
8  ALABAMA 2014 482           555           610           1298
9  ALABAMA 2016 513           583           566           1293
10 ALABAMA 2018 458           660           556           1340
11 ALABAMA 2020 431           599           626           1261
12 ALASKA  2000  58            NA            NA            144
13 ALASKA  2002  56            NA            NA            162
14 ALASKA  2004  60            NA            NA            166
15 ALASKA  2006  NA            NA            NA             NA
16 ALASKA  2008  NA            NA            NA            191
17 ALASKA  2010  66            NA            NA            182
18 ALASKA  2012  63           109            86            186
19 ALASKA  2014  76           111            78            189
20 ALASKA  2016  65           113            83            180
   TotPop_65 TotCPop_18to24 TotCPop_25to34 TotCPop_35to44 ⋯ is_2006 is_2008
1   NA       418             NA             NA            ⋯ 0       0
2   NA       385             NA             NA            ⋯ 0       0
3   NA       387             NA             NA            ⋯ 0       0
4   NA        NA             NA             NA            ⋯ 1       0
5   NA       441             NA             NA            ⋯ 0       1
6   NA       388             NA             NA            ⋯ 0       0
7  667       428            535            582            ⋯ 0       0
8  710       449            519            566            ⋯ 0       0
9  761       497            568            548            ⋯ 0       0
10 740       434            619            508            ⋯ 0       0
11 852       427            587            608            ⋯ 0       0
12  NA        55             NA             NA            ⋯ 0       0
13  NA        51             NA             NA            ⋯ 0       0
14  NA        58             NA             NA            ⋯ 0       0
15  NA        NA             NA             NA            ⋯ 1       0
16  44        NA             NA             NA            ⋯ 0       1
17  NA        64             NA             NA            ⋯ 0       0
18  72        61            103             80            ⋯ 0       0
19  66        74            107             75            ⋯ 0       0
20  77        65            109             79            ⋯ 0       0
   is_2010 is_2012 is_2014 is_2016 is_2018 is_2020 pres_year senate
1  0       0       0       0       0       0       1         0
2  0       0       0       0       0       0       0         1
3  0       0       0       0       0       0       1         1
4  0       0       0       0       0       0       0         0
5  0       0       0       0       0       0       1         0
6  1       0       0       0       0       0       0         1
7  0       1       0       0       0       0       1         0
8  0       0       1       0       0       0       0         1
9  0       0       0       1       0       0       1         1
10 0       0       0       0       1       0       0         1
11 0       0       0       0       0       1       1         1
12 0       0       0       0       0       0       1         0
13 0       0       0       0       0       0       0         1
14 0       0       0       0       0       0       1         1
15 0       0       0       0       0       0       0         0
16 0       0       0       0       0       0       1         1
17 1       0       0       0       0       0       0         1
18 0       1       0       0       0       0       1         0
19 0       0       1       0       0       0       0         1
20 0       0       0       1       0       0       1         1

## Swing State Dummies

In [39]:
#Making swing state dummies 
swing_2000 <- c("OREGON", "MINNESOTA", "WISCONSIN", "IOWA", "NEW MEXICO", "FLORIDA", "NEW HAMPSHIRE")
swing_2004 <- c("NEVADA", "WISCONSIN", "IOWA", "NEW MEXICO", "OHIO", "PENNSYLVANIA", "NEW HAMPSHIRE")
swing_2008 <- c("MONTANA", "INDIANA", "FLORIDA", "NORTH CAROLINA", "MISSOURI")
swing_2012 <- c("OHIO", "NORTH CAROLINA", "FLORIDA")

# Combine all swing state vectors into one
all_swing_states <- c(swing_2000, swing_2004, swing_2008, swing_2012)

In [40]:
final$swing_2000 <- ifelse(final$Year == 2000 & final$STATE %in% swing_2000, 1, 0)
final$swing_2004 <- ifelse(final$Year == 2004 & final$STATE %in% swing_2004, 1, 0)
final$swing_2008 <- ifelse(final$Year == 2008 & final$STATE %in% swing_2008, 1, 0)
final$swing_2012 <- ifelse(final$Year == 2012 & final$STATE %in% swing_2012, 1, 0)

# Create a new variable "swing_ever" in final dataframe
final$swing_ever <- ifelse(final$STATE %in% all_swing_states, 1, 0)

# Citizen Population

In [41]:
# Initialize a vector to store TotCPop_18to24_2012 values
totcpop_2012_values <- numeric(nrow(final))

# Iterate over each row of the final data frame
for (i in 1:nrow(final)) {
  # Find the value of TotCPop_18to24 for the corresponding state in the year 2012
  state <- final$STATE[i]
  totcpop_2012 <- final$TotCPop_18to24[final$STATE == state & final$Year == 2012]
  
  # Assign the value to the corresponding element in totcpop_2012_values
  if (length(totcpop_2012) > 0) {
    totcpop_2012_values[i] <- totcpop_2012
  } else {
    totcpop_2012_values[i] <- NA  # If no value found, assign NA
  }
}

# Assign the totcpop_2012_values vector to the TotCPop_18to24_2012 column in the final data frame
final$TotCPop_18to24_2012 <- totcpop_2012_values

In [42]:
head(final, 20)

   STATE   Year TotPop_18to24 TotPop_25to34 TotPop_35to44 TotPop_45to64
1  ALABAMA 2000 430            NA            NA           1063
2  ALABAMA 2002 396            NA            NA           1115
3  ALABAMA 2004 413            NA            NA           1131
4  ALABAMA 2006  NA            NA            NA             NA
5  ALABAMA 2008 458            NA            NA           1210
6  ALABAMA 2010 397            NA            NA           1254
7  ALABAMA 2012 439           576           615           1297
8  ALABAMA 2014 482           555           610           1298
9  ALABAMA 2016 513           583           566           1293
10 ALABAMA 2018 458           660           556           1340
11 ALABAMA 2020 431           599           626           1261
12 ALASKA  2000  58            NA            NA            144
13 ALASKA  2002  56            NA            NA            162
14 ALASKA  2004  60            NA            NA            166
15 ALASKA  2006  NA            NA            NA             NA
16 ALASKA  2008  NA            NA            NA            191
17 ALASKA  2010  66            NA            NA            182
18 ALASKA  2012  63           109            86            186
19 ALASKA  2014  76           111            78            189
20 ALASKA  2016  65           113            83            180
   TotPop_65 TotCPop_18to24 TotCPop_25to34 TotCPop_35to44 ⋯ is_2018 is_2020
1   NA       418             NA             NA            ⋯ 0       0
2   NA       385             NA             NA            ⋯ 0       0
3   NA       387             NA             NA            ⋯ 0       0
4   NA        NA             NA             NA            ⋯ 0       0
5   NA       441             NA             NA            ⋯ 0       0
6   NA       388             NA             NA            ⋯ 0       0
7  667       428            535            582            ⋯ 0       0
8  710       449            519            566            ⋯ 0       0
9  761       497            568            548            ⋯ 0       0
10 740       434            619            508            ⋯ 1       0
11 852       427            587            608            ⋯ 0       1
12  NA        55             NA             NA            ⋯ 0       0
13  NA        51             NA             NA            ⋯ 0       0
14  NA        58             NA             NA            ⋯ 0       0
15  NA        NA             NA             NA            ⋯ 0       0
16  44        NA             NA             NA            ⋯ 0       0
17  NA        64             NA             NA            ⋯ 0       0
18  72        61            103             80            ⋯ 0       0
19  66        74            107             75            ⋯ 0       0
20  77        65            109             79            ⋯ 0       0
   pres_year senate swing_2000 swing_2004 swing_2008 swing_2012 swing_ever
1  1         0      0          0          0          0          0
2  0         1      0          0          0          0          0
3  1         1      0          0          0          0          0
4  0         0      0          0          0          0          0
5  1         0      0          0          0          0          0
6  0         1      0          0          0          0          0
7  1         0      0          0          0          0          0
8  0         1      0          0          0          0          0
9  1         1      0          0          0          0          0
10 0         1      0          0          0          0          0
11 1         1      0          0          0          0          0
12 1         0      0          0          0          0          0
13 0         1      0          0          0          0          0
14 1         1      0          0          0          0          0
15 0         0      0          0          0          0          0
16 1         1      0          0          0          0          0
17 0         1      0          0          0          0          0
18 1         0      0          0          0          0          0
19 0         1      0          0          0          0          0
20 1         1      0          0          0          0          0
   TotCPop_18to24_2012
1  428
2  428
3  428
4  428
5  428
6  428
7  428
8  428
9  428
10 428
11 428
12  61
13  61
14  61
15  61
16  61
17  61
18  61
19  61
20  61

In [43]:
# Initialize a vector to store TotCPop_Blackaloneorincombination_2012 values
totcpop_2012_values <- numeric(nrow(final))

# Iterate over each row of the final data frame
for (i in 1:nrow(final)) {
  # Find the value of TotCPop_18to24 for the corresponding state in the year 2012
  state <- final$STATE[i]
  totcpop_2012 <- final$TotCPop_Blackaloneorincombination[final$STATE == state & final$Year == 2012]
  
  # Assign the value to the corresponding element in totcpop_2012_values
  if (length(totcpop_2012) > 0) {
    totcpop_2012_values[i] <- totcpop_2012
  } else {
    totcpop_2012_values[i] <- NA  # If no value found, assign NA
  }
}

# Assign the totcpop_2012_values vector to the TotCPop_18to24_2012 column in the final data frame
final$TotCPop_Blackaloneorincombination_2012 <- totcpop_2012_values

In [44]:
# Initialize a vector to store TotCPop_Total_2012 values
totcpop_2012_values <- numeric(nrow(final))

# Iterate over each row of the final data frame
for (i in 1:nrow(final)) {
  # Find the value of TotCPop_18to24 for the corresponding state in the year 2012
  state <- final$STATE[i]
  totcpop_2012 <- final$TotCPop_Total[final$STATE == state & final$Year == 2012]
  
  # Assign the value to the corresponding element in totcpop_2012_values
  if (length(totcpop_2012) > 0) {
    totcpop_2012_values[i] <- totcpop_2012
  } else {
    totcpop_2012_values[i] <- NA  # If no value found, assign NA
  }
}

# Assign the totcpop_2012_values vector to the TotCPop_18to24_2012 column in the final data frame
final$TotCPop_Total_2012 <- totcpop_2012_values

In [45]:
# Initialize a vector to store TotPop_Total_2012 values
totcpop_2012_values <- numeric(nrow(final))

# Iterate over each row of the final data frame
for (i in 1:nrow(final)) {
  # Find the value of TotCPop_18to24 for the corresponding state in the year 2012
  state <- final$STATE[i]
  totcpop_2012 <- final$TotPop_Total[final$STATE == state & final$Year == 2012]
  
  # Assign the value to the corresponding element in totcpop_2012_values
  if (length(totcpop_2012) > 0) {
    totcpop_2012_values[i] <- totcpop_2012
  } else {
    totcpop_2012_values[i] <- NA  # If no value found, assign NA
  }
}

# Assign the totcpop_2012_values vector to the TotCPop_18to24_2012 column in the final data frame
final$TotPop_Total_2012 <- totcpop_2012_values

In [46]:
# Initialize a vector to store TotPop_Whitealoneorincombination_2012 values
totcpop_2012_values <- numeric(nrow(final))

# Iterate over each row of the final data frame
for (i in 1:nrow(final)) {
  # Find the value of TotCPop_18to24 for the corresponding state in the year 2012
  state <- final$STATE[i]
  totcpop_2012 <- final$TotCPop_Whitealoneorincombination[final$STATE == state & final$Year == 2012]
  
  # Assign the value to the corresponding element in totcpop_2012_values
  if (length(totcpop_2012) > 0) {
    totcpop_2012_values[i] <- totcpop_2012
  } else {
    totcpop_2012_values[i] <- NA  # If no value found, assign NA
  }
}

# Assign the totcpop_2012_values vector to the TotCPop_18to24_2012 column in the final data frame
final$TotCPop_Whitealoneorincombination_2012 <- totcpop_2012_values

In [47]:
# Initialize a vector to store TotPop_45to64_2012 values
totcpop_2012_values <- numeric(nrow(final))

# Iterate over each row of the final data frame
for (i in 1:nrow(final)) {
  # Find the value of TotCPop_18to24 for the corresponding state in the year 2012
  state <- final$STATE[i]
  totcpop_2012 <- final$TotCPop_45to64[final$STATE == state & final$Year == 2012]
  
  # Assign the value to the corresponding element in totcpop_2012_values
  if (length(totcpop_2012) > 0) {
    totcpop_2012_values[i] <- totcpop_2012
  } else {
    totcpop_2012_values[i] <- NA  # If no value found, assign NA
  }
}

# Assign the totcpop_2012_values vector to the TotCPop_18to24_2012 column in the final data frame
final$TotCPop_45to64_2012 <- totcpop_2012_values

In [48]:
head(final, 10)

   STATE   Year TotPop_18to24 TotPop_25to34 TotPop_35to44 TotPop_45to64
1  ALABAMA 2000 430            NA            NA           1063
2  ALABAMA 2002 396            NA            NA           1115
3  ALABAMA 2004 413            NA            NA           1131
4  ALABAMA 2006  NA            NA            NA             NA
5  ALABAMA 2008 458            NA            NA           1210
6  ALABAMA 2010 397            NA            NA           1254
7  ALABAMA 2012 439           576           615           1297
8  ALABAMA 2014 482           555           610           1298
9  ALABAMA 2016 513           583           566           1293
10 ALABAMA 2018 458           660           556           1340
   TotPop_65 TotCPop_18to24 TotCPop_25to34 TotCPop_35to44 ⋯ swing_2004
1   NA       418             NA             NA            ⋯ 0
2   NA       385             NA             NA            ⋯ 0
3   NA       387             NA             NA            ⋯ 0
4   NA        NA             NA             NA            ⋯ 0
5   NA       441             NA             NA            ⋯ 0
6   NA       388             NA             NA            ⋯ 0
7  667       428            535            582            ⋯ 0
8  710       449            519            566            ⋯ 0
9  761       497            568            548            ⋯ 0
10 740       434            619            508            ⋯ 0
   swing_2008 swing_2012 swing_ever TotCPop_18to24_2012
1  0          0          0          428
2  0          0          0          428
3  0          0          0          428
4  0          0          0          428
5  0          0          0          428
6  0          0          0          428
7  0          0          0          428
8  0          0          0          428
9  0          0          0          428
10 0          0          0          428
   TotCPop_Blackaloneorincombination_2012 TotCPop_Total_2012 TotPop_Total_2012
1  897                                    3479               3594
2  897                                    3479               3594
3  897                                    3479               3594
4  897                                    3479               3594
5  897                                    3479               3594
6  897                                    3479               3594
7  897                                    3479               3594
8  897                                    3479               3594
9  897                                    3479               3594
10 897                                    3479               3594
   TotCPop_Whitealoneorincombination_2012 TotCPop_45to64_2012
1  2527                                   1275
2  2527                                   1275
3  2527                                   1275
4  2527                                   1275
5  2527                                   1275
6  2527                                   1275
7  2527                                   1275
8  2527                                   1275
9  2527                                   1275
10 2527                                   1275

## Education Data

In [49]:
write.csv(read_excel("C:\\Users\\joyse\\Desktop\\14.33\\Data\\education_data.xls"), "C:\\Users\\joyse\\Desktop\\14.33\\Data\\education_data.csv", row.names = FALSE)

New names:
• `` -> `...2`
• `` -> `...3`
• `` -> `...4`
• `` -> `...5`
• `` -> `...6`
• `` -> `...7`
• `` -> `...8`
• `` -> `...9`
• `` -> `...10`
• `` -> `...11`
• `` -> `...12`
• `` -> `...13`
• `` -> `...14`
• `` -> `...15`
• `` -> `...16`
• `` -> `...17`
• `` -> `...18`
• `` -> `...19`
• `` -> `...20`
• `` -> `...21`
• `` -> `...22`
• `` -> `...23`
• `` -> `...24`
• `` -> `...25`

In [50]:
education_data <- read.csv("C:\\Users\\joyse\\Desktop\\14.33\\Data\\education_data.csv", skip=9)
education_data <- education_data[-(63:nrow(education_data)), ]
head(education_data)

  X1                            X2       NA.        X3      NA..1   X4
1 United States ........        74.74970 0.01867234 82.8629 0.06295 19.6
2 NA                                  NA         NA      NA      NA   NA
3 Alabama ....................  72.24769 0.15144749 79.8926 0.52677 24.7
4 Alaska ..................     76.92768 0.39503373 80.3566 1.37005 11.7
5 Arizona ..................... 69.24535 0.18752165 77.5145 0.42711 19.0
6 Arkansas ..................   75.42820 0.18801913 81.5492 0.54833 24.7
  NA..2       X5   NA..3       X6   ⋯ X9      NA..7   X10     NA..8   X11
1 0.006576016 80.4 0.006576016 24.4 ⋯ 15.4479 0.02779 84.5521 0.02779 27.4147
2          NA   NA          NA   NA ⋯      NA      NA      NA      NA      NA
3 0.056775380 75.3 0.056775380 19.0 ⋯ 19.1327 0.20173 80.8673 0.20173 21.5353
4 0.116515784 88.3 0.116515784 24.7 ⋯  9.2930 0.35897 90.7070 0.35897 26.4069
5 0.063230592 81.0 0.063230592 23.5 ⋯ 16.3864 0.16390 83.6136 0.16390 25.3952
6 0.073283064 75.3 0.073283064 16.7 ⋯ 18.6975 0.22949 81.3025 0.22949 19.0002
  NA..9   X12     NA..10  X13     NA..11
1 0.03648 17.3479 0.02329 10.0667 0.02049
2      NA      NA      NA      NA      NA
3 0.17030 13.7798 0.15017  7.7555 0.10645
4 0.52148 16.6100 0.37493  9.7968 0.35329
5 0.13021 16.1754 0.12358  9.2198 0.07252
6 0.22002 12.5839 0.18131  6.4163 0.13126

In [51]:
#Getting rid of the standard deviation columns 
columns_to_delete <- c(3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25)  # Specify the indices of the columns you want to delete
education_data <- education_data[, -columns_to_delete]  # Remove the specified columns

In [52]:
head(education_data)

  X1                            X2       X3      X4   X5   X6   X7   X8
1 United States ........        74.74970 82.8629 19.6 80.4 24.4 15.5 8.9
2 NA                                  NA      NA   NA   NA   NA   NA  NA
3 Alabama ....................  72.24769 79.8926 24.7 75.3 19.0 12.1 6.9
4 Alaska ..................     76.92768 80.3566 11.7 88.3 24.7 16.1 8.6
5 Arizona ..................... 69.24535 77.5145 19.0 81.0 23.5 15.1 8.4
6 Arkansas ..................   75.42820 81.5492 24.7 75.3 16.7 11.0 5.7
  X9      X10     X11     X12     X13
1 15.4479 84.5521 27.4147 17.3479 10.0667
2      NA      NA      NA      NA      NA
3 19.1327 80.8673 21.5353 13.7798  7.7555
4  9.2930 90.7070 26.4069 16.6100  9.7968
5 16.3864 83.6136 25.3952 16.1754  9.2198
6 18.6975 81.3025 19.0002 12.5839  6.4163

In [53]:
#Naming the columns 
col_names <- c("STATE", "Percent_18to24_CompleteHS_2000", "Percent_18to24_CompleteHS_2006to2008", 
              "Percent_25andOver_LessThanHS_2000", "Percent_25andOver_HSorMore_2000", 
              "Percent_25andOver_BachelororMore_2000",  "Percent_25andOver_JustBachelor_2000", 
               "Percent_25andOver_JustGradDegree_2000", "Percent_25andOver_LessThanHS_2006to2008", 
               "Percent_25andOver_HSorMore_2006to2008", "Percent_25andOver_BachelororMore_2006to2008", 
               "Percent_25andOver_JustBachelor_2006to2008", "Percent_25andOver_JustGradDegree_2006to2008")
colnames(education_data) <- col_names

In [54]:
head(education_data)

  STATE                         Percent_18to24_CompleteHS_2000
1 United States ........        74.74970
2 NA                                  NA
3 Alabama ....................  72.24769
4 Alaska ..................     76.92768
5 Arizona ..................... 69.24535
6 Arkansas ..................   75.42820
  Percent_18to24_CompleteHS_2006to2008 Percent_25andOver_LessThanHS_2000
1 82.8629                              19.6
2      NA                                NA
3 79.8926                              24.7
4 80.3566                              11.7
5 77.5145                              19.0
6 81.5492                              24.7
  Percent_25andOver_HSorMore_2000 Percent_25andOver_BachelororMore_2000
1 80.4                            24.4
2   NA                              NA
3 75.3                            19.0
4 88.3                            24.7
5 81.0                            23.5
6 75.3                            16.7
  Percent_25andOver_JustBachelor_2000 Percent_25andOver_JustGradDegree_2000
1 15.5                                8.9
2   NA                                 NA
3 12.1                                6.9
4 16.1                                8.6
5 15.1                                8.4
6 11.0                                5.7
  Percent_25andOver_LessThanHS_2006to2008 Percent_25andOver_HSorMore_2006to2008
1 15.4479                                 84.5521
2      NA                                      NA
3 19.1327                                 80.8673
4  9.2930                                 90.7070
5 16.3864                                 83.6136
6 18.6975                                 81.3025
  Percent_25andOver_BachelororMore_2006to2008
1 27.4147
2      NA
3 21.5353
4 26.4069
5 25.3952
6 19.0002
  Percent_25andOver_JustBachelor_2006to2008
1 17.3479
2      NA
3 13.7798
4 16.6100
5 16.1754
6 12.5839
  Percent_25andOver_JustGradDegree_2006to2008
1 10.0667
2      NA
3  7.7555
4  9.7968
5  9.2198
6  6.4163

In [55]:
# Deleting the periods in the State column 
education_data$STATE <- gsub("\\.", "", education_data$STATE)

In [56]:
head(education_data, 30)

   STATE                 Percent_18to24_CompleteHS_2000
1  United States         74.74970
2  NA                          NA
3  Alabama               72.24769
4  Alaska                76.92768
5  Arizona               69.24535
6  Arkansas              75.42820
7  California            70.73952
8  NA                          NA
9  Colorado              75.06749
10 Connecticut           78.21647
11 Delaware              77.61536
12 District of Columbia  79.37753
13 Florida               71.74017
14 NA                          NA
15 Georgia               70.03656
16 Hawaii                85.84129
17 Idaho                 77.30865
18 Illinois              75.99273
19 Indiana               76.49255
20 NA                          NA
21 Iowa                  81.44995
22 Kansas                78.30835
23 Kentucky              74.93319
24 Louisiana             72.31478
25 Maine                 78.90190
26 NA                          NA
27 Maryland              79.62800
28 Massachusetts         82.21210
29 Michigan              76.45595
30 Minnesota             79.28808
   Percent_18to24_CompleteHS_2006to2008 Percent_25andOver_LessThanHS_2000
1  82.8629                              19.6
2       NA                                NA
3  79.8926                              24.7
4  80.3566                              11.7
5  77.5145                              19.0
6  81.5492                              24.7
7  81.7570                              23.2
8       NA                                NA
9  82.9009                              13.1
10 87.3390                              16.0
11 81.9157                              17.4
12 86.4360                              22.2
13 80.6403                              20.1
14      NA                                NA
15 78.3622                              21.4
16 90.5510                              15.4
17 83.6612                              15.3
18 84.1699                              18.6
19 81.0302                              17.9
20      NA                                NA
21 87.9023                              13.9
22 85.7521                              14.0
23 82.5802                              25.9
24 77.5073                              25.2
25 84.9782                              14.6
26      NA                                NA
27 85.5821                              16.2
28 87.6002                              15.2
29 83.9624                              16.6
30 86.6964                              12.1
   Percent_25andOver_HSorMore_2000 Percent_25andOver_BachelororMore_2000
1  80.4                            24.4
2    NA                              NA
3  75.3                            19.0
4  88.3                            24.7
5  81.0                            23.5
6  75.3                            16.7
7  76.8                            26.6
8    NA                              NA
9  86.9                            32.7
10 84.0                            31.4
11 82.6                            25.0
12 77.8                            39.1
13 79.9                            22.3
14   NA                              NA
15 78.6                            24.3
16 84.6                            26.2
17 84.7                            21.7
18 81.4                            26.1
19 82.1                            19.4
20   NA                              NA
21 86.1                            21.2
22 86.0                            25.8
23 74.1                            17.1
24 74.8                            18.7
25 85.4                            22.9
26   NA                              NA
27 83.8                            31.4
28 84.8                            33.2
29 83.4                            21.8
30 87.9                            27.4
   Percent_25andOver_JustBachelor_2000 Percent_25andOver_JustGradDegree_2000
1  15.5                                 8.9
2    NA                                  NA
3  12.1                                 6.9
4  16.1                                 8.6
5  15.1                                 8.4
6  11.0                                 5.7
7  17.1                                 9.5
8    NA                                  NA
9  21.6                                11.1
10 18.1                                13.3
11 15.6                                 9.4
12 18.1                                21.0
13 14.2                                 8.1
14   NA                                  NA
15 16.0                                 8.3
16 17.8                                 8.4
17 14.9                                 6.8
18 16.6                                 9.5
19 12.2                                 7.2
20   NA                                  NA
21 14.7                                 6.5
22 17.1                                 8.7
23 10.2                                 6.9
24 12.2                                 6.5
25 15.0                                 7.9
26   NA                                  NA
27 18.0                                13.4
28 19.5                                13.7
29 13.7                                 8.1
30 19.1                                 8.3
   Percent_25andOver_LessThanHS_2006to2008
1  15.4479
2       NA
3  19.1327
4   9.2930
5  16.3864
6  18.6975
7  19.7015
8       NA
9  11.3967
10 11.6985
11 13.4991
12 14.7710
13 15.0293
14      NA
15 17.0531
16 10.4679
17 12.0178
18 14.4107
19 14.1872
20      NA
21 10.4147
22 10.9727
23 19.5005
24 19.9102
25 10.6251
26      NA
27 12.4886
28 11.6331
29 12.3477
30  8.9495
   Percent_25andOver_HSorMore_2006to2008
1  84.5521
2       NA
3  80.8673
4  90.7070
5  83.6136
6  81.3025
7  80.2985
8       NA
9  88.6033
10 88.3015
11 86.5009
12 85.2290
13 84.9707
14      NA
15 82.9469
16 89.5321
17 87.9822
18 85.5893
19 85.8128
20      NA
21 89.5853
22 89.0273
23 80.4995
24 80.0898
25 89.3749
26      NA
27 87.5114
28 88.3669
29 87.6523
30 91.0505
   Percent_25andOver_BachelororMore_2006to2008
1  27.4147
2       NA
3  21.5353
4  26.4069
5  25.3952
6  19.0002
7  29.4346
8       NA
9  35.0556
10 34.7545
11 26.8073
12 46.9346
13 25.6691
14      NA
15 26.8572
16 29.0459
17 24.1250
18 29.4980
19 22.4578
20      NA
21 24.1653
22 29.1735
23 19.9425
24 20.3336
25 25.6083
26      NA
27 35.2703
28 37.7268
29 24.7959
30 30.9779
   Percent_25andOver_JustBachelor_2006to2008
1  17.3479
2       NA
3  13.7798
4  16.6100
5  16.1754
6  12.5839
7  18.8537
8       NA
9  22.6394
10 19.8923
11 16.1258
12 20.7759
13 16.7175
14      NA
15 17.4734
16 19.2134
17 16.6524
18 18.4733
19 14.3626
20      NA
21 16.8115
22 19.2583
23 11.9758
24 13.6401
25 16.6054
26      NA
27 19.6126
28 21.7748
29 15.3959
30 21.1460
   Percent_25andOver_JustGradDegree_2006to2008
1  10.0667
2       NA
3   7.7555
4   9.7968
5   9.2198
6   6.4163
7  10.5809
8       NA
9  12.4162
10 14.8622
11 10.6815
12 26.1587
13  8.9515
14      NA
15  9.3838
16  9.8324
17  7.4727
18 11.0247
19  8.0952
20      NA
21  7.3539
22  9.9152
23  7.9667
24  6.6935
25  9.0029
26      NA
27 15.6577
28 15.9520
29  9.4000
30  9.8319

In [57]:
# Deleting NA rows
education_data <- education_data[complete.cases(education_data$STATE), ]

In [58]:
head(education_data)

  STATE          Percent_18to24_CompleteHS_2000
1 United States  74.74970
3 Alabama        72.24769
4 Alaska         76.92768
5 Arizona        69.24535
6 Arkansas       75.42820
7 California     70.73952
  Percent_18to24_CompleteHS_2006to2008 Percent_25andOver_LessThanHS_2000
1 82.8629                              19.6
3 79.8926                              24.7
4 80.3566                              11.7
5 77.5145                              19.0
6 81.5492                              24.7
7 81.7570                              23.2
  Percent_25andOver_HSorMore_2000 Percent_25andOver_BachelororMore_2000
1 80.4                            24.4
3 75.3                            19.0
4 88.3                            24.7
5 81.0                            23.5
6 75.3                            16.7
7 76.8                            26.6
  Percent_25andOver_JustBachelor_2000 Percent_25andOver_JustGradDegree_2000
1 15.5                                8.9
3 12.1                                6.9
4 16.1                                8.6
5 15.1                                8.4
6 11.0                                5.7
7 17.1                                9.5
  Percent_25andOver_LessThanHS_2006to2008 Percent_25andOver_HSorMore_2006to2008
1 15.4479                                 84.5521
3 19.1327                                 80.8673
4  9.2930                                 90.7070
5 16.3864                                 83.6136
6 18.6975                                 81.3025
7 19.7015                                 80.2985
  Percent_25andOver_BachelororMore_2006to2008
1 27.4147
3 21.5353
4 26.4069
5 25.3952
6 19.0002
7 29.4346
  Percent_25andOver_JustBachelor_2006to2008
1 17.3479
3 13.7798
4 16.6100
5 16.1754
6 12.5839
7 18.8537
  Percent_25andOver_JustGradDegree_2006to2008
1 10.0667
3  7.7555
4  9.7968
5  9.2198
6  6.4163
7 10.5809

In [59]:
#Making the state words capital case
education_data$STATE <- toupper(education_data$STATE)

In [60]:
# Getting rid of the trailing spaces in the States
education_data$STATE <- trimws(education_data$STATE)

In [61]:
head(education_data)

  STATE         Percent_18to24_CompleteHS_2000
1 UNITED STATES 74.74970
3 ALABAMA       72.24769
4 ALASKA        76.92768
5 ARIZONA       69.24535
6 ARKANSAS      75.42820
7 CALIFORNIA    70.73952
  Percent_18to24_CompleteHS_2006to2008 Percent_25andOver_LessThanHS_2000
1 82.8629                              19.6
3 79.8926                              24.7
4 80.3566                              11.7
5 77.5145                              19.0
6 81.5492                              24.7
7 81.7570                              23.2
  Percent_25andOver_HSorMore_2000 Percent_25andOver_BachelororMore_2000
1 80.4                            24.4
3 75.3                            19.0
4 88.3                            24.7
5 81.0                            23.5
6 75.3                            16.7
7 76.8                            26.6
  Percent_25andOver_JustBachelor_2000 Percent_25andOver_JustGradDegree_2000
1 15.5                                8.9
3 12.1                                6.9
4 16.1                                8.6
5 15.1                                8.4
6 11.0                                5.7
7 17.1                                9.5
  Percent_25andOver_LessThanHS_2006to2008 Percent_25andOver_HSorMore_2006to2008
1 15.4479                                 84.5521
3 19.1327                                 80.8673
4  9.2930                                 90.7070
5 16.3864                                 83.6136
6 18.6975                                 81.3025
7 19.7015                                 80.2985
  Percent_25andOver_BachelororMore_2006to2008
1 27.4147
3 21.5353
4 26.4069
5 25.3952
6 19.0002
7 29.4346
  Percent_25andOver_JustBachelor_2006to2008
1 17.3479
3 13.7798
4 16.6100
5 16.1754
6 12.5839
7 18.8537
  Percent_25andOver_JustGradDegree_2006to2008
1 10.0667
3  7.7555
4  9.7968
5  9.2198
6  6.4163
7 10.5809

In [62]:
head(final)

  STATE   Year TotPop_18to24 TotPop_25to34 TotPop_35to44 TotPop_45to64
1 ALABAMA 2000 430           NA            NA            1063
2 ALABAMA 2002 396           NA            NA            1115
3 ALABAMA 2004 413           NA            NA            1131
4 ALABAMA 2006  NA           NA            NA              NA
5 ALABAMA 2008 458           NA            NA            1210
6 ALABAMA 2010 397           NA            NA            1254
  TotPop_65 TotCPop_18to24 TotCPop_25to34 TotCPop_35to44 ⋯ swing_2004
1 NA        418            NA             NA             ⋯ 0
2 NA        385            NA             NA             ⋯ 0
3 NA        387            NA             NA             ⋯ 0
4 NA         NA            NA             NA             ⋯ 0
5 NA        441            NA             NA             ⋯ 0
6 NA        388            NA             NA             ⋯ 0
  swing_2008 swing_2012 swing_ever TotCPop_18to24_2012
1 0          0          0          428
2 0          0          0          428
3 0          0          0          428
4 0          0          0          428
5 0          0          0          428
6 0          0          0          428
  TotCPop_Blackaloneorincombination_2012 TotCPop_Total_2012 TotPop_Total_2012
1 897                                    3479               3594
2 897                                    3479               3594
3 897                                    3479               3594
4 897                                    3479               3594
5 897                                    3479               3594
6 897                                    3479               3594
  TotCPop_Whitealoneorincombination_2012 TotCPop_45to64_2012
1 2527                                   1275
2 2527                                   1275
3 2527                                   1275
4 2527                                   1275
5 2527                                   1275
6 2527                                   1275

In [63]:
#Merging the two 
merged_data <- merge(final, education_data, by = "STATE", all = TRUE)

In [64]:
head(merged_data)

  STATE   Year TotPop_18to24 TotPop_25to34 TotPop_35to44 TotPop_45to64
1 ALABAMA 2000 430           NA            NA            1063
2 ALABAMA 2002 396           NA            NA            1115
3 ALABAMA 2004 413           NA            NA            1131
4 ALABAMA 2006  NA           NA            NA              NA
5 ALABAMA 2008 458           NA            NA            1210
6 ALABAMA 2010 397           NA            NA            1254
  TotPop_65 TotCPop_18to24 TotCPop_25to34 TotCPop_35to44 ⋯
1 NA        418            NA             NA             ⋯
2 NA        385            NA             NA             ⋯
3 NA        387            NA             NA             ⋯
4 NA         NA            NA             NA             ⋯
5 NA        441            NA             NA             ⋯
6 NA        388            NA             NA             ⋯
  Percent_25andOver_LessThanHS_2000 Percent_25andOver_HSorMore_2000
1 24.7                              75.3
2 24.7                              75.3
3 24.7                              75.3
4 24.7                              75.3
5 24.7                              75.3
6 24.7                              75.3
  Percent_25andOver_BachelororMore_2000 Percent_25andOver_JustBachelor_2000
1 19                                    12.1
2 19                                    12.1
3 19                                    12.1
4 19                                    12.1
5 19                                    12.1
6 19                                    12.1
  Percent_25andOver_JustGradDegree_2000 Percent_25andOver_LessThanHS_2006to2008
1 6.9                                   19.1327
2 6.9                                   19.1327
3 6.9                                   19.1327
4 6.9                                   19.1327
5 6.9                                   19.1327
6 6.9                                   19.1327
  Percent_25andOver_HSorMore_2006to2008
1 80.8673
2 80.8673
3 80.8673
4 80.8673
5 80.8673
6 80.8673
  Percent_25andOver_BachelororMore_2006to2008
1 21.5353
2 21.5353
3 21.5353
4 21.5353
5 21.5353
6 21.5353
  Percent_25andOver_JustBachelor_2006to2008
1 13.7798
2 13.7798
3 13.7798
4 13.7798
5 13.7798
6 13.7798
  Percent_25andOver_JustGradDegree_2006to2008
1 7.7555
2 7.7555
3 7.7555
4 7.7555
5 7.7555
6 7.7555

# GDP Per Cap Data

In [65]:
gdp_data <- read.csv("C:\\Users\\joyse\\Desktop\\14.33\\Data\\gsp_naics_all_pc\\gsp_naics_all_PC.csv")
gdp_data <- gdp_data[-(53:nrow(gdp_data)), ]
head(gdp_data)
tail(gdp_data, 20)

  GeoFIPS GeoName       Region ComponentId ComponentName
1 00000   United States NA     1000        Per capita real GDP by state
2 01000   Alabama        5     1000        Per capita real GDP by state
3 02000   Alaska         8     1000        Per capita real GDP by state
4 04000   Arizona        6     1000        Per capita real GDP by state
5 05000   Arkansas       5     1000        Per capita real GDP by state
6 06000   California     8     1000        Per capita real GDP by state
  IndustryId IndustryClassification Description        X1997 X1998 ⋯ X2003
1 1          ...                    All industry total 36150 37270 ⋯ 40706
2 1          ...                    All industry total 28055 28676 ⋯ 31091
3 1          ...                    All industry total 60768 57007 ⋯ 55964
4 1          ...                    All industry total 29866 31693 ⋯ 36276
5 1          ...                    All industry total 27507 27662 ⋯ 30481
6 1          ...                    All industry total 36636 38502 ⋯ 43956
  X2004 X2005 X2006 X2007 X2008 X2009 X2010 X2011 X2012
1 41664 42431 43152 43499 42805 41049 41694 42069 42784
2 32431 33036 33200 33253 33036 31493 32148 32354 32615
3 57909 56638 58990 59817 59697 63264 60873 61202 61156
4 36673 38117 39536 39553 38395 34905 34463 34676 35195
5 31298 31822 32200 32054 31872 30991 31516 31547 31837
6 45560 47141 48456 48646 47976 45105 44793 44898 46029

   GeoFIPS GeoName        Region ComponentId ComponentName
33 35000   New Mexico     6      1000        Per capita real GDP by state
34 36000   New York       2      1000        Per capita real GDP by state
35 37000   North Carolina 5      1000        Per capita real GDP by state
36 38000   North Dakota   4      1000        Per capita real GDP by state
37 39000   Ohio           3      1000        Per capita real GDP by state
38 40000   Oklahoma       6      1000        Per capita real GDP by state
39 41000   Oregon         8      1000        Per capita real GDP by state
40 42000   Pennsylvania   2      1000        Per capita real GDP by state
41 44000   Rhode Island   1      1000        Per capita real GDP by state
42 45000   South Carolina 5      1000        Per capita real GDP by state
43 46000   South Dakota   4      1000        Per capita real GDP by state
44 47000   Tennessee      5      1000        Per capita real GDP by state
45 48000   Texas          6      1000        Per capita real GDP by state
46 49000   Utah           7      1000        Per capita real GDP by state
47 50000   Vermont        1      1000        Per capita real GDP by state
48 51000   Virginia       5      1000        Per capita real GDP by state
49 53000   Washington     8      1000        Per capita real GDP by state
50 54000   West Virginia  5      1000        Per capita real GDP by state
51 55000   Wisconsin      3      1000        Per capita real GDP by state
52 56000   Wyoming        7      1000        Per capita real GDP by state
   IndustryId IndustryClassification Description        X1997 X1998 ⋯ X2003
33 1          ...                    All industry total 30001 30220 ⋯ 33696
34 1          ...                    All industry total 41160 42087 ⋯ 46615
35 1          ...                    All industry total 35262 36069 ⋯ 38946
36 1          ...                    All industry total 29842 31654 ⋯ 37503
37 1          ...                    All industry total 35199 36258 ⋯ 37933
38 1          ...                    All industry total 30046 30430 ⋯ 33234
39 1          ...                    All industry total 30974 32190 ⋯ 36403
40 1          ...                    All industry total 34092 35317 ⋯ 38157
41 1          ...                    All industry total 33633 34161 ⋯ 40366
42 1          ...                    All industry total 30428 31148 ⋯ 33375
43 1          ...                    All industry total 30039 31867 ⋯ 39801
44 1          ...                    All industry total 33075 33983 ⋯ 36053
45 1          ...                    All industry total 38206 39760 ⋯ 41528
46 1          ...                    All industry total 32456 33810 ⋯ 35273
47 1          ...                    All industry total 28969 30123 ⋯ 34966
48 1          ...                    All industry total 37708 39081 ⋯ 44275
49 1          ...                    All industry total 39435 41144 ⋯ 42921
50 1          ...                    All industry total 26049 26636 ⋯ 27904
51 1          ...                    All industry total 34092 35212 ⋯ 38182
52 1          ...                    All industry total 42937 43930 ⋯ 50961
   X2004 X2005 X2006 X2007 X2008 X2009 X2010 X2011 X2012
33 35550 35069 35284 35008 34340 34485 34263 33872 33900
34 47949 50169 52308 52771 51396 50452 52242 52657 53067
35 39264 40741 41443 41546 40590 39390 39821 39627 40289
36 37252 38183 38879 40436 43530 44359 46867 49847 55250
37 38557 38739 38280 38331 37350 35171 35881 36892 37690
38 33965 33965 35305 35713 36633 35523 35349 35726 36252
39 39085 39696 42956 43759 45156 43247 45375 46573 48069
40 38576 38731 39061 39586 39503 38105 38806 39455 40063
41 41288 41379 42287 42025 41160 40565 41000 41061 41678
42 33066 33225 33022 33293 32273 30483 30926 31345 31881
43 40184 40682 40411 41455 42925 42567 42090 43561 43181
44 37095 37437 37831 37275 36942 35189 35763 36370 37254
45 43088 42521 43507 44964 44310 43221 44203 45025 46498
46 35678 36870 38226 38995 39001 37770 37903 38373 39158
47 36195 36610 36940 36603 36485 35383 37291 37736 38198
48 45457 47032 47328 47329 46779 45891 47042 47118 47127
49 43066 44641 45637 47315 46963 45113 45631 45942 47146
50 28315 28485 28771 28465 28034 28078 28891 29427 30389
51 38944 39431 39865 39885 38788 37499 38491 38845 39308
52 51985 51054 54968 55748 57447 57942 56689 54969 54305

In [66]:
#Making the state words capital case 
gdp_data$GeoName <- toupper(gdp_data$GeoName)

In [67]:
# Only keeping relevant columns 
columns_to_keep <- c('GeoName', paste0('X', 2000:2012))

# Filter the dataframe to keep only the specified columns
filtered_gdp_data <- gdp_data %>%
  select(columns_to_keep)

# Rename the columns
new_column_names <- c('GeoName', paste0('rGDPperCap_', 2000:2012))
filtered_gdp_data <- rename(filtered_gdp_data, !!!setNames(columns_to_keep, new_column_names))
head(filtered_gdp_data)

Warning message:
"Using an external vector in selections was deprecated in tidyselect 1.1.0.
ℹ Please use `all_of()` or `any_of()` instead.
  # Was:
  data %>% select(columns_to_keep)

  # Now:
  data %>% select(all_of(columns_to_keep))

See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>."

  GeoName       rGDPperCap_2000 rGDPperCap_2001 rGDPperCap_2002 rGDPperCap_2003
1 UNITED STATES 39783           39882           40191           40706
2 ALABAMA       29805           29968           30599           31091
3 ALASKA        54449           56380           57774           55964
4 ARIZONA       34656           35169           35207           36276
5 ARKANSAS      28948           29146           29780           30481
6 CALIFORNIA    43319           42748           43090           43956
  rGDPperCap_2004 rGDPperCap_2005 rGDPperCap_2006 rGDPperCap_2007
1 41664           42431           43152           43499
2 32431           33036           33200           33253
3 57909           56638           58990           59817
4 36673           38117           39536           39553
5 31298           31822           32200           32054
6 45560           47141           48456           48646
  rGDPperCap_2008 rGDPperCap_2009 rGDPperCap_2010 rGDPperCap_2011
1 42805           41049           41694           42069
2 33036           31493           32148           32354
3 59697           63264           60873           61202
4 38395           34905           34463           34676
5 31872           30991           31516           31547
6 47976           45105           44793           44898
  rGDPperCap_2012
1 42784
2 32615
3 61156
4 35195
5 31837
6 46029

In [68]:
final_merged_data <- merge(merged_data, filtered_gdp_data, by.x = "STATE", by.y = "GeoName", all.x = TRUE)

In [69]:
head(final_merged_data)

  STATE   Year TotPop_18to24 TotPop_25to34 TotPop_35to44 TotPop_45to64
1 ALABAMA 2000 430           NA            NA            1063
2 ALABAMA 2002 396           NA            NA            1115
3 ALABAMA 2004 413           NA            NA            1131
4 ALABAMA 2006  NA           NA            NA              NA
5 ALABAMA 2008 458           NA            NA            1210
6 ALABAMA 2010 397           NA            NA            1254
  TotPop_65 TotCPop_18to24 TotCPop_25to34 TotCPop_35to44 ⋯ rGDPperCap_2003
1 NA        418            NA             NA             ⋯ 31091
2 NA        385            NA             NA             ⋯ 31091
3 NA        387            NA             NA             ⋯ 31091
4 NA         NA            NA             NA             ⋯ 31091
5 NA        441            NA             NA             ⋯ 31091
6 NA        388            NA             NA             ⋯ 31091
  rGDPperCap_2004 rGDPperCap_2005 rGDPperCap_2006 rGDPperCap_2007
1 32431           33036           33200           33253
2 32431           33036           33200           33253
3 32431           33036           33200           33253
4 32431           33036           33200           33253
5 32431           33036           33200           33253
6 32431           33036           33200           33253
  rGDPperCap_2008 rGDPperCap_2009 rGDPperCap_2010 rGDPperCap_2011
1 33036           31493           32148           32354
2 33036           31493           32148           32354
3 33036           31493           32148           32354
4 33036           31493           32148           32354
5 33036           31493           32148           32354
6 33036           31493           32148           32354
  rGDPperCap_2012
1 32615
2 32615
3 32615
4 32615
5 32615
6 32615

# Covid Controls

In [70]:
covid_data <- read.csv("C:\\Users\\joyse\\Desktop\\14.33\\Data\\covid_mortality.csv")

In [71]:
head(covid_data)

  YEAR STATE RATE  DEATHS URL
1 2021 AL    152.8  9491  /nchs/pressroom/states/alabama/al.htm
2 2021 AK    109.5   763  /nchs/pressroom/states/alaska/ak.htm
3 2021 AZ    139.5 12706  /nchs/pressroom/states/arizona/az.htm
4 2021 AR    127.7  4739  /nchs/pressroom/states/arkansas/ar.htm
5 2021 CA     99.9 44540  /nchs/pressroom/states/california/ca.htm
6 2021 CO     84.2  5299  /nchs/pressroom/states/colorado/co.htm

In [72]:
covid_data_2020 <- covid_data %>%
  filter(YEAR == 2020)

In [73]:
covid_data_2020

   YEAR STATE RATE  DEATHS URL
1  2020 AL    103.6  6544  /nchs/pressroom/states/alabama/al.htm
2  2020 AK     35.7   230  /nchs/pressroom/states/alaska/ak.htm
3  2020 AZ     87.6  8447  /nchs/pressroom/states/arizona/az.htm
4  2020 AR     90.2  3523  /nchs/pressroom/states/arkansas/ar.htm
5  2020 CA     68.7 31335  /nchs/pressroom/states/california/ca.htm
6  2020 CO     69.6  4315  /nchs/pressroom/states/colorado/co.htm
7  2020 CT    112.3  5782  /nchs/pressroom/states/connecticut/ct.htm
8  2020 DE     73.4  1008  /nchs/pressroom/states/delaware/de.htm
9  2020 FL     56.4 19231  /nchs/pressroom/states/florida/fl.htm
10 2020 GA     81.7  9453  /nchs/pressroom/states/georgia/ga.htm
11 2020 HI     16.8   342  /nchs/pressroom/states/hawaii/hi.htm
12 2020 ID     63.9  1358  /nchs/pressroom/states/idaho/id.htm
13 2020 IL     99.2 15735  /nchs/pressroom/states/illinois/il.htm
14 2020 IN    103.2  8527  /nchs/pressroom/states/indiana/in.htm
15 2020 IA     99.0  4336  /nchs/pressroom/states/iowa/ia.htm
16 2020 KS     90.5  3344  /nchs/pressroom/states/kansas/ks.htm
17 2020 KY     74.2  4132  /nchs/pressroom/states/kentucky/ky.htm
18 2020 LA    118.0  6533  /nchs/pressroom/states/louisiana/la.htm
19 2020 ME     20.2   420  /nchs/pressroom/states/maine/me.htm
20 2020 MD     80.9  6000  /nchs/pressroom/states/maryland/md.htm
21 2020 MA    100.2  9319  /nchs/pressroom/states/massachusetts/ma.htm
22 2020 MI     85.9 11391  /nchs/pressroom/states/michigan/mi.htm
23 2020 MN     71.9  5215  /nchs/pressroom/states/minnesota/mn.htm
24 2020 MS    123.5  4466  /nchs/pressroom/states/mississippi/ms.htm
25 2020 MO     87.1  7137  /nchs/pressroom/states/missouri/mo.htm
26 2020 MT     75.5  1119  /nchs/pressroom/states/montana/mt.htm
27 2020 NE     84.4  2043  /nchs/pressroom/states/nebraska/ne.htm
28 2020 NV     88.4  3238  /nchs/pressroom/states/nevada/nv.htm
29 2020 NH     40.9   779  /nchs/pressroom/states/newhampshire/nh.htm
30 2020 NJ    141.6 16497  /nchs/pressroom/states/newjersey/nj.htm
31 2020 NM    106.2  2841  /nchs/pressroom/states/newmexico/nm.htm
32 2020 NY    139.1 35736  /nchs/pressroom/states/newyork/ny.htm
33 2020 NC     60.4  7892  /nchs/pressroom/states/northcarolina/nc.htm
34 2020 ND    121.9  1210  /nchs/pressroom/states/northdakota/nd.htm
35 2020 OH     87.3 13605  /nchs/pressroom/states/ohio/oh.htm
36 2020 OK    100.3  4847  /nchs/pressroom/states/oklahoma/ok.htm
37 2020 OR     26.0  1434  /nchs/pressroom/states/oregon/or.htm
38 2020 PA     88.1 16609  /nchs/pressroom/states/pennsylvania/pa.htm
39 2020 RI    104.3  1585  /nchs/pressroom/states/rhodeisland/ri.htm
40 2020 SC     77.7  5277  /nchs/pressroom/states/southcarolina/sc.htm
41 2020 SD    127.0  1496  /nchs/pressroom/states/southdakota/sd.htm
42 2020 TN     80.3  6838  /nchs/pressroom/states/tennessee/tn.htm
43 2020 TX    105.2 30840  /nchs/pressroom/states/texas/tx.htm
44 2020 UT     48.6  1365  /nchs/pressroom/states/utah/ut.htm
45 2020 VT     16.0   144  /nchs/pressroom/states/vermont/vt.htm
46 2020 VA     56.3  5821  /nchs/pressroom/states/virginia/va.htm
47 2020 WA     36.7  3284  /nchs/pressroom/states/washington/wa.htm
48 2020 WV     56.2  1483  /nchs/pressroom/states/westvirginia/wv.htm
49 2020 WI     70.2  5432  /nchs/pressroom/states/wisconsin/wi.htm
50 2020 WY     63.1   462  /nchs/pressroom/states/wyoming/wy.htm

In [74]:
# Mapping of state abbreviations to full names
state_mapping <- c("AL" = "ALABAMA",
                    "AK" = "ALASKA",
                    "AZ" = "ARIZONA",
                    "AR" = "ARKANSAS",
                    "CA" = "CALIFORNIA",
                    "CO" = "COLORADO",
                    "CT" = "CONNECTICUT",
                    "DE" = "DELAWARE",
                    "FL" = "FLORIDA",
                    "GA" = "GEORGIA",
                    "HI" = "HAWAII",
                    "ID" = "IDAHO",
                    "IL" = "ILLINOIS",
                    "IN" = "INDIANA",
                    "IA" = "IOWA",
                    "KS" = "KANSAS",
                    "KY" = "KENTUCKY",
                    "LA" = "LOUISIANA",
                    "ME" = "MAINE",
                    "MD" = "MARYLAND",
                    "MA" = "MASSACHUSETTS",
                    "MI" = "MICHIGAN",
                    "MN" = "MINNESOTA",
                    "MS" = "MISSISSIPPI",
                    "MO" = "MISSOURI",
                    "MT" = "MONTANA",
                    "NE" = "NEBRASKA",
                    "NV" = "NEVADA",
                    "NH" = "NEW HAMPSHIRE",
                    "NJ" = "NEW JERSEY",
                    "NM" = "NEW MEXICO",
                    "NY" = "NEW YORK",
                    "NC" = "NORTH CAROLINA",
                    "ND" = "NORTH DAKOTA",
                    "OH" = "OHIO",
                    "OK" = "OKLAHOMA",
                    "OR" = "OREGON",
                    "PA" = "PENNSYLVANIA",
                    "RI" = "RHODE ISLAND",
                    "SC" = "SOUTH CAROLINA",
                    "SD" = "SOUTH DAKOTA",
                    "TN" = "TENNESSEE",
                    "TX" = "TEXAS",
                    "UT" = "UTAH",
                    "VT" = "VERMONT",
                    "VA" = "VIRGINIA",
                    "WA" = "WASHINGTON",
                    "WV" = "WEST VIRGINIA",
                    "WI" = "WISCONSIN",
                    "WY" = "WYOMING")

# Replace state abbreviations with full state names
covid_data_2020$STATE <- toupper(state_mapping[as.character(covid_data_2020$STATE)])
covid_data_2020 <- covid_data_2020 %>%
  rename(Covid_mrate_2020 = RATE)

In [75]:
covid_data_2020

   YEAR STATE          Covid_mrate_2020 DEATHS
1  2020 ALABAMA        103.6             6544
2  2020 ALASKA          35.7              230
3  2020 ARIZONA         87.6             8447
4  2020 ARKANSAS        90.2             3523
5  2020 CALIFORNIA      68.7            31335
6  2020 COLORADO        69.6             4315
7  2020 CONNECTICUT    112.3             5782
8  2020 DELAWARE        73.4             1008
9  2020 FLORIDA         56.4            19231
10 2020 GEORGIA         81.7             9453
11 2020 HAWAII          16.8              342
12 2020 IDAHO           63.9             1358
13 2020 ILLINOIS        99.2            15735
14 2020 INDIANA        103.2             8527
15 2020 IOWA            99.0             4336
16 2020 KANSAS          90.5             3344
17 2020 KENTUCKY        74.2             4132
18 2020 LOUISIANA      118.0             6533
19 2020 MAINE           20.2              420
20 2020 MARYLAND        80.9             6000
21 2020 MASSACHUSETTS  100.2             9319
22 2020 MICHIGAN        85.9            11391
23 2020 MINNESOTA       71.9             5215
24 2020 MISSISSIPPI    123.5             4466
25 2020 MISSOURI        87.1             7137
26 2020 MONTANA         75.5             1119
27 2020 NEBRASKA        84.4             2043
28 2020 NEVADA          88.4             3238
29 2020 NEW HAMPSHIRE   40.9              779
30 2020 NEW JERSEY     141.6            16497
31 2020 NEW MEXICO     106.2             2841
32 2020 NEW YORK       139.1            35736
33 2020 NORTH CAROLINA  60.4             7892
34 2020 NORTH DAKOTA   121.9             1210
35 2020 OHIO            87.3            13605
36 2020 OKLAHOMA       100.3             4847
37 2020 OREGON          26.0             1434
38 2020 PENNSYLVANIA    88.1            16609
39 2020 RHODE ISLAND   104.3             1585
40 2020 SOUTH CAROLINA  77.7             5277
41 2020 SOUTH DAKOTA   127.0             1496
42 2020 TENNESSEE       80.3             6838
43 2020 TEXAS          105.2            30840
44 2020 UTAH            48.6             1365
45 2020 VERMONT         16.0              144
46 2020 VIRGINIA        56.3             5821
47 2020 WASHINGTON      36.7             3284
48 2020 WEST VIRGINIA   56.2             1483
49 2020 WISCONSIN       70.2             5432
50 2020 WYOMING         63.1              462
   URL
1  /nchs/pressroom/states/alabama/al.htm
2  /nchs/pressroom/states/alaska/ak.htm
3  /nchs/pressroom/states/arizona/az.htm
4  /nchs/pressroom/states/arkansas/ar.htm
5  /nchs/pressroom/states/california/ca.htm
6  /nchs/pressroom/states/colorado/co.htm
7  /nchs/pressroom/states/connecticut/ct.htm
8  /nchs/pressroom/states/delaware/de.htm
9  /nchs/pressroom/states/florida/fl.htm
10 /nchs/pressroom/states/georgia/ga.htm
11 /nchs/pressroom/states/hawaii/hi.htm
12 /nchs/pressroom/states/idaho/id.htm
13 /nchs/pressroom/states/illinois/il.htm
14 /nchs/pressroom/states/indiana/in.htm
15 /nchs/pressroom/states/iowa/ia.htm
16 /nchs/pressroom/states/kansas/ks.htm
17 /nchs/pressroom/states/kentucky/ky.htm
18 /nchs/pressroom/states/louisiana/la.htm
19 /nchs/pressroom/states/maine/me.htm
20 /nchs/pressroom/states/maryland/md.htm
21 /nchs/pressroom/states/massachusetts/ma.htm
22 /nchs/pressroom/states/michigan/mi.htm
23 /nchs/pressroom/states/minnesota/mn.htm
24 /nchs/pressroom/states/mississippi/ms.htm
25 /nchs/pressroom/states/missouri/mo.htm
26 /nchs/pressroom/states/montana/mt.htm
27 /nchs/pressroom/states/nebraska/ne.htm
28 /nchs/pressroom/states/nevada/nv.htm
29 /nchs/pressroom/states/newhampshire/nh.htm
30 /nchs/pressroom/states/newjersey/nj.htm
31 /nchs/pressroom/states/newmexico/nm.htm
32 /nchs/pressroom/states/newyork/ny.htm
33 /nchs/pressroom/states/northcarolina/nc.htm
34 /nchs/pressroom/states/northdakota/nd.htm
35 /nchs/pressroom/states/ohio/oh.htm
36 /nchs/pressroom/states/oklahoma/ok.htm
37 /nchs/pressroom/states/oregon/or.htm
38 /nchs/pressroom/states/pennsylvania/pa.htm
39 /nchs/pressroom/states/rhodeisland/ri.htm
40 /nchs/pressroom/states/southcarolina/sc.htm
41 /nchs/pressroom/states/southdakota/sd.htm
42 /nchs/pressroom/states/tennessee/tn.htm
43 /nchs/pressroom/states/texas/tx.htm
44 /nchs/pressroom/states/utah/ut.htm
45 /nchs/pressroom/states/vermont/vt.htm
46 /nchs/pressroom/states/virginia/va.htm
47 /nchs/pressroom/states/washington/wa.htm
48 /nchs/pressroom/states/westvirginia/wv.htm
49 /nchs/pressroom/states/wisconsin/wi.htm
50 /nchs/pressroom/states/wyoming/wy.htm

In [76]:
covid_data_2020 <- covid_data_2020[, c("STATE", "Covid_mrate_2020")]

In [77]:
final_merged_data <- merge(final_merged_data, covid_data_2020, by.x = "STATE", all.x = TRUE)

In [78]:
#Checking
tail(final_merged_data)

    STATE   Year TotPop_18to24 TotPop_25to34 TotPop_35to44 TotPop_45to64
557 WYOMING 2010 51            NA            NA            154
558 WYOMING 2012 56            73            68            155
559 WYOMING 2014 52            80            73            153
560 WYOMING 2016 57            75            70            151
561 WYOMING 2018 44            84            67            142
562 WYOMING 2020 52            74            70            145
    TotPop_65 TotCPop_18to24 TotCPop_25to34 TotCPop_35to44 ⋯ rGDPperCap_2004
557 NA        45             NA             NA             ⋯ 51985
558 74        55             71             66             ⋯ 51985
559 82        51             75             70             ⋯ 51985
560 83        55             73             68             ⋯ 51985
561 94        44             80             65             ⋯ 51985
562 96        51             69             69             ⋯ 51985
    rGDPperCap_2005 rGDPperCap_2006 rGDPperCap_2007 rGDPperCap_2008
557 51054           54968           55748           57447
558 51054           54968           55748           57447
559 51054           54968           55748           57447
560 51054           54968           55748           57447
561 51054           54968           55748           57447
562 51054           54968           55748           57447
    rGDPperCap_2009 rGDPperCap_2010 rGDPperCap_2011 rGDPperCap_2012
557 57942           56689           54969           54305
558 57942           56689           54969           54305
559 57942           56689           54969           54305
560 57942           56689           54969           54305
561 57942           56689           54969           54305
562 57942           56689           54969           54305
    Covid_mrate_2020
557 63.1
558 63.1
559 63.1
560 63.1
561 63.1
562 63.1

In [79]:
#Making sure excluded territories are still excluded after all the merges
final_merged_data <- final_merged_data[!(final_merged_data$STATE %in% exclude), ]

In [80]:
write.csv(final_merged_data, "C:\\Users\\joyse\\Desktop\\14.33\\Data\\final_merge_withoutB_controls.csv")